// 메인 section2 best data
const m_bestData = {
    bestItem0: [
        {   name: "베이직 스트랩 샌들 1.5",
            img: "./images/goods/women/best/item_7.jpg",
            oprice: "29900",
            dprice: "19900",
            review: "8",
        },
        {   name: "라운드 투스트랩 밴딩 슬라이드 1.0",
            img: "./images/goods/women/best/item_11.jpg",
            oprice: "19900",
            dprice: "9900",
            review: "12",
        },
        {   name: "[시누 PICK] 경량EVA 논슬립 베이직 리커버리 쪼리",
            img: "./images/goods/women/best/item_1.jpg",
            oprice: "19900",
            dprice: "15900",
            review: "2",
        },
        {   name: "[테니스클럽] 베이직 덱 스니커즈 (듀얼쿠션)",
            img: "./images/goods/women/best/item_3.jpg",
            oprice: "29900",
            dprice: "19900",
            review: "4",
        },
    ],
    bestItem1: [
        {   name: "소프트 퀼팅백",
            img: "./images/goods/women/best/item_5.jpg",
            oprice:"49900",
            dprice:"39900",
            review:"6",
        },
        {   name: "✔MD 추천✔ 소프트 미니 퀼팅백",
            img: "./images/goods/women/best/item_8.jpg",
            oprice: "39900",
            dprice: "29900",
            review: "9",
        },
        {   name: "캔버스 쇼퍼백",
            img: "./images/goods/women/best/item_12.jpg",
            oprice: "39900",
            dprice: "25900",
            review: "13",
        },
        {   name: "나일론 탑 스트링 백팩",
            img: "./images/goods/women/best/item_9.jpg",
            oprice: "39900",
            dprice: "35900",
            review: "19",
        },
    ],
    bestItem2: [
        {   name: "리커버리 소프트 젤리 샌들",
            img: "./images/goods/women/shoes/sandal/item_6_on.jpg",
            oprice:"19900",
            dprice:"17910",
            review:"",
        },
        {   name: "사선 스트랩 쪼리 젤리 샌들",
            img: "./images/goods/women/shoes/sandal/item_8_on.jpg",
            oprice:"19900",
            dprice:"17910",
            review:"",
        },
        {   name: "[경량EVA] 논슬립 베이직 리커버리 쪼리",
            img: "./images/goods/men/shoes/slippers/item_3_on.jpg",
            oprice: "19900",
            dprice: "15900",
            review: "59",
        },
        {   name: "키즈 리커버리 슬리퍼",
            img: "./images/goods/kids/shoes/sandal/item_11_on.jpg",
            oprice: "15900",
            dprice: "9900",
            review: "61",
        },
    ],
};

// main sc3 media data
const mData = [
    {
        thumbImg: "ban1.jpg",
        depth1: ["ban1.jpg","페이퍼 블렌디드 선캡","15900"],
        depth2: ["ban1.jpg","라탄 숄더백","29900"],
    },
    {
        thumbImg: "ban2.jpg",
        depth1: ["ban2.jpg","스윗버튼 메리제인","26900"],
        depth2: ["ban2.jpg","스퀘어 미디엄 숄더백","27900"],
    },
    {
        thumbImg: "ban3.jpg",
        depth1: ["ban3.jpg","모노 메리제인","37900"],
        depth2: ["ban3.jpg","모노 메리제인 1.0","37900"],
    },
    {
        thumbImg: "ban4.jpg",
        depth1: ["ban4.jpg","토캡 버클 메리제인 1.0","37900"],
        depth2: ["ban4.jpg","🌟뉴컬러🌟 바게트 숄더백","29900"],
    },
    {
        thumbImg: "ban5.jpg",
        depth1: ["ban5.jpg","3단 스트라이프 썸머 크로쉐햇","27900"],
        depth2: ["ban5.jpg","패턴 커버 슬라이드 1.0","19900"],
    },
    {
        thumbImg: "ban6.jpg",
        depth1: ["ban6.jpg","썸머 베이직 크로셰햇","19900"],
        depth2: ["ban6.jpg","[경량EVA] 솔리드 볼드 슬라이드","18900"],
    },
    {
        thumbImg: "ban7.jpg",
        depth1: ["ban7.jpg","경량EVA 논슬립 베이직 리커버리 쪼리","15900"],
        depth2: ["ban7.jpg","경량EVA 논슬립 베이직 리커버리 쪼리","15900"],
    },
    {
        thumbImg: "ban8.jpg",
        depth1: ["ban8.jpg","[경량EVA] 플로우 리커버리 클로그","25900"],
        depth2: ["ban8.jpg","[경량EVA] 플로우 리커버리 클로그","25900"],
    },
    {
        thumbImg: "ban9.jpg",
        depth1: ["ban9.jpg","[버블 폼폼] 링클 미니 호보백","22900"],
        depth2: ["ban9.jpg","오버솔 6CM 리프트 스니커즈","44900"],
    },
    {
        thumbImg: "ban10.jpg",
        depth1: ["ban10.jpg","캔버스 버킷백","29900"],
        depth2: ["ban10.jpg","캔버스 쇼퍼백","25900"],
    },
];

// 메인 section4
const m_newData = {
    // women data
    newItem0: [
        {   name: "미니 스퀘어 크로스백",
            img: "./images/goods/women/new/item_6.jpg",
            oprice: "39900",
            dprice: "36900",
            review: "58",
        },
        {   name: "스퀘어 미니 토트백",
            img: "./images/goods/women/new/item_7.jpg",
            oprice: "29900",
            dprice: "27900",
            review: "21",
        },
        {   name: "스퀘어 리본 투웨이 샌들",
            img: "./images/goods/women/new/item_13.jpg",
            oprice: "37000",
            dprice: "29800",
            review: "62",
        },
        {   name: "청키 트랙솔 메리제인 5.0",
            img: "./images/goods/women/new/item_9.jpg",
            oprice: "49900",
            dprice: "46900",
            review: "23",
        },
    ],
    // men data
    newItem1: [
        {   name: "오솔라이트 유니 레더 독일군",
            img: "./images/goods/men/new/item_4.jpg",
            oprice: "59900",
            dprice: "56900",
            review: "18",
        },
        {   name: "무지 코튼 라운드 버킷햇",
            img: "./images/goods/men/new/item_13.jpg",
            oprice: "39900",
            dprice: "29900",
            review: "104",
        },
        {   name: "크로스 스트랩 슬라이드",
            img: "./images/goods/men/new/item_11.jpg",
            oprice: "19900",
            dprice: "15900",
            review: "43",
        },
        {   name: "유니레더 NEW ARMY 독일군 스니커즈",
            img: "./images/goods/men/new/item_6.jpg",
            oprice: "59900",
            dprice: "45520",
            review: "64",
        },
    ],
    // kids data
    newItem2: [
        {   name: "키즈 독일군 스니커즈",
            img: "./images/goods/kids/new/item_4.jpg",
            oprice: "35900",
            dprice: "32300",
            review: "15",
        },
        {   name: "키즈 그래픽 밸크로 실내화",
            img: "./images/goods/kids/new/item_11.jpg",
            oprice: "12900",
            dprice: "9900",
            review: "74",
        },
        {   name: "키즈 글리터 리본 쿠션 플랫",
            img: "./images/goods/kids/new/item_3.jpg",
            oprice: "23900",
            dprice: "21510",
            review: "42",
        },
        {   name: "플랫폼 스트랩 구두",
            img: "./images/goods/kids/new/item_7.jpg",
            oprice: "36900",
            dprice: "33210",
            review: "81",
        },
    ],
};

const mapData = [
    // 서울
    {
        mtit: "미아점",
        maddr: "서울특별시 강북구 도봉로 52 (미아동) 지하2층",
        // msrc: ,
        mtel: "02-6312-6281",
    },
    {
        mtit: "NC백화점 송파점",
        maddr: "서울시 송파구 충민로 66 (문정동) NC백화점 송파점 패션관 1층",
        // msrc: ,
        mtel: "02-2157-5252",
    },
    {
        mtit: "홍대점",
        maddr: "서울특별시 마포구 양화로 153(동교동) 1층",
        // msrc: ,
        mtel: "02-338-5751",
    },
    {
        mtit: "2001아울렛 천호점",
        maddr: "서울특별시 강동구 구천면로 189 (천호동, 동아코아아파트)  2001아울렛 천호점 1층",
        // msrc: ,
        mtel: "02-2224-6586",
    },
    {
        mtit: "아이파크몰 용산점",
        maddr: "서울특별시 용산구 한강대로23길 55 아이파크백화점 패션관 2층",
        // msrc: ,
        mtel: "02-2012-3780",
    },
    {
        mtit: "타임스퀘어 영등포점",
        maddr: "서울특별시 영등포구 영중로 15 (영등포동4가) 타음스퀘어 영등포점 지하1층",
        // msrc: ,
        mtel: "02-2069-4105",
    },
    // 부산
    {
        mtit: "NC백화점 부산대점",
        maddr: "부산광역시 금정구 장전동 40 NC백화점 부산대점 1층",
        // msrc: ,
        mtel: "051-794-7052",
    },
    {
        mtit: "뉴코아아울렛 덕천점",
        maddr: "부산광역시 북구 만덕대로 23 (덕천동) 뉴코아아울렛 덕천점 5층 비아니키즈",
        // msrc: ,
        mtel: "051-509-7035",
    },
    {
        mtit: "부산 아트몰링점",
        maddr: "부산광역시 사하구 낙동남로 1413 (하단동) 6층",
        // msrc: ,
        mtel: "051-999-7399",
    },
    {
        mtit: "NC백화점 서면점",
        maddr: "부산광역시 부산진구 동천로 92 (전포동) NC백화점 서면점 1층",
        // msrc: ,
        mtel: "051-794-7052",
    },
    {
        mtit: "NC백화점 해운대점",
        maddr: "부산광역시 해운대구 좌동 1467-4 NC백화점 해운대점 1층",
        // msrc: ,
        mtel: "051-709-5572",
    },
    // 인천
    {
        mtit: "스퀘어원 연수점",
        maddr: "인천광역시 연수구 청능대로 210 스퀘어원몰 2층",
        // msrc: ,
        mtel: "032-456-4271",
    },
    {
        mtit: "비아니키즈 뉴코아아울렛 논현점",
        maddr: "인천광역시 남동구 청능대로 596 (논현동) 뉴코아아울렛 논현점 2층 ",
        // msrc: ,
        mtel: "032-454-8315",
    },
]

export {m_bestData, m_newData, mData, mapData};