// 남성 더미데이터 - mmenData.js
const menData = {
    // 1. 신발데이터
    shoes: {
        // 1-1. 스니커즈
        "스니커즈": [
            {   idx: 0,
                name: "[슈탠다드] 와이드핏 캔버스 스니커즈",
                img: "men/shoes/sneakers/item_1",
                sumimg2: "men/shoes/sneakers/sum2/item_1",
                sumimg3: "men/shoes/sneakers/sum3/item_1",
                oprice: "29900",
                dprice: "27900",
                review: "126",
                color: ["White", "Black", "Red", "Ivory", "Green"],
                size: ["230", "240", "250", "260", "270", "280"],
            },
            {   idx: 1,
                name: "[슈탠다드] 베이직 캔버스 스니커즈",
                img: "men/shoes/sneakers/item_2",
                sumimg2: "men/shoes/sneakers/sum2/item_2",
                sumimg3: "men/shoes/sneakers/sum3/item_2",
                oprice: "29900",
                dprice: "27900",
                review: "98",
                color: ["White", "Black", "Light Gray", "Red", "Light Pink", "Light Beige", "Navy", "Dark Red"],
                size: ["220", "230", "240", "250", "260", "270", "280"],
            },
            {   idx: 2,
                name: "🌟BEST [오솔라이트] 유니 레더 독일군",
                img: "men/shoes/sneakers/item_3",
                sumimg2: "men/shoes/sneakers/sum2/item_3",
                sumimg3: "men/shoes/sneakers/sum3/item_3",
                oprice: "59900",
                dprice: "49900",
                review: "13",
                color: ["White", "Beige", "Navy", "Cream", "Brown"],
                size: ["250", "260", "270", "280", "290"],
            },
            {   idx: 3,
                name: "니트 밴드 슬립온 워킹화",
                img: "men/shoes/sneakers/item_4",
                sumimg2: "men/shoes/sneakers/sum2/item_4",
                sumimg3: "men/shoes/sneakers/sum3/item_4",
                oprice: "39900",
                dprice: "23900",
                review: "6",
                color: ["White", "Gray", "Black", "Mint Green"],
                size: ["220", "230", "240", "250", "260", "270", "280"],
            },
            {   idx: 4,
                name: "베이직 키높이 스니커즈",
                img: "men/shoes/sneakers/item_5",
                sumimg2: "men/shoes/sneakers/sum2/item_5",
                sumimg3: "men/shoes/sneakers/sum3/item_5",
                oprice: "59900",
                dprice: "35900",
                review: "14",
                color: ["White", "White Edge"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 5,
                name: "[NAVY] 베이직 캔버스 덱 슈즈",
                img: "men/shoes/sneakers/item_6",
                sumimg2: "men/shoes/sneakers/sum2/item_6",
                sumimg3: "men/shoes/sneakers/sum3/item_6",
                oprice: "29900",
                dprice: "17900",
                review: "63",
                color: ["Navy", "Black", "Dark Red", "Off White"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 6,
                name: "라이트 플랫폼 스니커즈",
                img: "men/shoes/sneakers/item_7",
                sumimg2: "men/shoes/sneakers/sum2/item_7",
                sumimg3: "men/shoes/sneakers/sum3/item_7",
                oprice: "19900",
                dprice: "14880",
                review: "15",
                color: ["White", "Black"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 7,
                name: "소프트 슬림 베이직 스니커즈",
                img: "men/shoes/sneakers/item_8",
                sumimg2: "men/shoes/sneakers/sum2/item_8",
                sumimg3: "men/shoes/sneakers/sum3/item_8",
                oprice: "59900",
                dprice: "49900",
                review: "95",
                color: ["White", "Black"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 8,
                name: "이지 라이트 컴포트 컬러믹스 캐주얼 더비",
                img: "men/shoes/sneakers/item_9",
                sumimg2: "men/shoes/sneakers/sum2/item_9",
                sumimg3: "men/shoes/sneakers/sum3/item_9",
                oprice: "49900",
                dprice: "29900",
                review: "16",
                color: ["Melange Gray", "Navy"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 9,
                name: "하이크 런 다이얼 트레킹화",
                img: "men/shoes/sneakers/item_10",
                sumimg2: "men/shoes/sneakers/sum2/item_10",
                sumimg3: "men/shoes/sneakers/sum3/item_10",
                oprice: "49900",
                dprice: "29900",
                review: "42",
                color: ["Gray", "Black", "Navy"],
                size: ["250", "260", "270", "280"],
            },
        ],
        // 1-2. 슬리퍼
        "슬리퍼": [
            {   idx: 0,
                name: "남성 피셔맨 오픈 슬라이드",
                img: "men/shoes/slippers/item_1",
                sumimg2: "men/shoes/slippers/sum2/item_1",
                sumimg3: "men/shoes/slippers/sum3/item_1",
                oprice: "49900",
                dprice: "46900",
                review: "5",
                color: ["Black", "Khaki"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 1,
                name: "[핏더사이즈] 남성 리커버리 슬라이드",
                img: "men/shoes/slippers/item_2",
                sumimg2: "men/shoes/slippers/sum2/item_2",
                sumimg3: "men/shoes/slippers/sum3/item_2",
                oprice: "39900",
                dprice: "35900",
                review: "12",
                color: ["Black", "Dark Beige", "Royal Blue", "Orange"],
                size: ["250", "260", "270", "280", "290"],
            },
            {   idx: 2,
                name: "논슬립 베이직 리커버리 쪼리",
                img: "men/shoes/slippers/item_3",
                sumimg2: "men/shoes/slippers/sum2/item_3",
                sumimg3: "men/shoes/slippers/sum3/item_3",
                oprice: "19900",
                dprice: "15900",
                review: "59",
                color: ["Black", "Dark Gray", "Light Pink", "Cream", "Neon Green"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 3,
                name: "[경량EVA] 논슬립 베이직 리커버리 쪼리",
                img: "men/shoes/slippers/item_4",
                sumimg2: "men/shoes/slippers/sum2/item_4",
                sumimg3: "men/shoes/slippers/sum3/item_4",
                oprice: "19900",
                dprice: "15900",
                review: "6",
                color: ["Black", "Dark Gray", "Light Beige", "Cream"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 4,
                name: "뉴덮개 슬리퍼",
                img: "men/shoes/slippers/item_5",
                sumimg2: "men/shoes/slippers/sum2/item_5",
                sumimg3: "men/shoes/slippers/sum3/item_5",
                oprice: "15900",
                dprice: "12900",
                review: "42",
                color: ["Beige", "Khaki"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 5,
                name: "슈펜 X 비슬로우 리커버리 슬라이더",
                img: "men/shoes/slippers/item_6",
                sumimg2: "men/shoes/slippers/sum2/item_6",
                sumimg3: "men/shoes/slippers/sum3/item_6",
                oprice: "19900",
                dprice: "11900",
                review: "32",
                color: ["Black", "Beige"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 6,
                name: "남성 베이직 쿠션 조리",
                img: "men/shoes/slippers/item_7",
                sumimg2: "men/shoes/slippers/sum2/item_7",
                sumimg3: "men/shoes/slippers/sum3/item_7",
                oprice: "49900",
                dprice: "29900",
                review: "4",
                color: ["Beige", "Khaki"],
                size: ["250", "260", "270", "280"],
            },
            {   idx: 7,
                name: "크로스 스트랩 슬라이드",
                img: "men/shoes/slippers/item_8",
                sumimg2: "men/shoes/slippers/sum2/item_8",
                sumimg3: "men/shoes/slippers/sum3/item_8",
                oprice: "39900",
                dprice: "35900",
                review: "13",
                color: ["Black", "Cream"],
                size: ["230", "240", "250", "260", "270", "280"],
            },
            {   idx: 8,
                name: "[경량EVA] 어글리 리커버리 쪼리",
                img: "men/shoes/slippers/item_9",
                sumimg2: "men/shoes/slippers/sum2/item_9",
                sumimg3: "men/shoes/slippers/sum3/item_9",
                oprice: "19900",
                dprice: "18900",
                review: "53",
                color: ["White", "Black", "Light Beige", "Khaki", "Dark Orange"],
                size: ["230", "240", "250", "260", "270", "280"],
            },
            {   idx: 9,
                name: "[경량EVA] 플로우 리커버리 클로그",
                img: "men/shoes/slippers/item_10",
                sumimg2: "men/shoes/slippers/sum2/item_10",
                sumimg3: "men/shoes/slippers/sum3/item_10",
                oprice: "35900",
                dprice: "25900",
                review: "42",
                color: ["Black", "Light Blue", "Cream"],
                size: ["230", "240", "250", "260"],
            },
        ],
    },
    // 2. 가방데이터
    bag: {
        // 2-1. 맨즈백
        "맨즈백": [
            {   idx: 0,
                name: "SHOO 나일론 럭색",
                img: "men/bag/mensbag/item_1",
                sumimg2: "men/bag/mensbag/sum2/item_1",
                sumimg3: "men/bag/mensbag/sum3/item_1",
                oprice: "69900",
                dprice: "48900",
                review: "106", 
                color: ["Black"],
                size: ["FREE"],
            },
            {   idx: 1,
                name: "SHOO 클러치",
                img: "men/bag/mensbag/item_2",
                sumimg2: "men/bag/mensbag/sum2/item_2",
                sumimg3: "men/bag/mensbag/sum3/item_2",
                oprice: "39900",
                dprice: "27900",
                review: "56", 
                color: ["Black", "Gray"],
                size: ["FREE"],
            },
        ],
        // 2-2. 크로스백
        "크로스백": [
            {   idx: 0,
                name: "[NAVY] 가벼운 반달포켓 크로스백",
                img: "men/bag/crossbag/item_1",
                sumimg2: "men/bag/crossbag/sum2/item_1",
                sumimg3: "men/bag/crossbag/sum3/item_1",
                oprice: "29900",
                dprice: "19900",
                review: "19",
                color: ["Gray", "Black", "Beige"],
                size: ["FREE"],
            },
            {   idx: 1,
                name: "[NAVY] 2포켓 빅 반달 메신저백",
                img: "men/bag/crossbag/item_2",
                sumimg2: "men/bag/crossbag/sum2/item_2",
                sumimg3: "men/bag/crossbag/sum3/item_2",
                oprice: "39900",
                dprice: "29900",
                review: "31",
                color: ["Gray", "Black"],
                size: ["FREE"],
            },
            {   idx: 2,
                name: "네이비 X 가벼운 크로스백",
                img: "men/bag/crossbag/item_3",
                sumimg2: "men/bag/crossbag/sum2/item_3",
                sumimg3: "men/bag/crossbag/sum3/item_3",
                oprice: "29900",
                dprice: "20900",
                review: "73",
                color: ["Gray", "Black"],
                size: ["FREE"],
            },
            {   idx: 3,
                name: "전황일 패딩 버킷백",
                img: "men/bag/crossbag/item_4",
                sumimg2: "men/bag/crossbag/sum2/item_4",
                sumimg3: "men/bag/crossbag/sum3/item_4",
                oprice: "25900",
                dprice: "17900",
                review: "16",
                color: ["Black", "Redish Brown", "Beige", "Mustard", "Khaki"],
                size: ["FREE"],
            },
        ],
    },
    // 3. 잡화데이터
    ac: {
        // 3-1. 양말
        "양말": [
            {   idx: 0,
                name: "슈탠다드 양말_남녀 클래식 골지 7팩",
                img: "men/ac/socks/item_1",
                sumimg2: "men/ac/socks/sum2/item_1",
                sumimg3: "men/ac/socks/sum3/item_1",
                oprice: "12900",
                dprice: "9900",
                review: "1", 
                color: ["Black", "Yellow", "Blue", "Ivory", "Two_tone"],
                size: ["24호", "26호"],
            },
            {   idx: 1,
                name: "슈탠다드 페이크 삭스 5팩",
                img: "men/ac/socks/item_2",
                sumimg2: "men/ac/socks/sum2/item_2",
                sumimg3: "men/ac/socks/sum3/item_2",
                oprice: "9900",
                dprice: "7900",
                review: "8", 
                color: ["Black", "Gray"],
                size: ["24호", "26호"],
            },
            {   idx: 2,
                name: "슈탠다드 양말 남녀 하프삭스 7팩",
                img: "men/ac/socks/item_3",
                sumimg2: "men/ac/socks/sum2/item_3",
                sumimg3: "men/ac/socks/sum3/item_3",
                oprice: "17900",
                dprice: "13900",
                review: "15", 
                color: ["Black", "Gray"],
                size: ["24호", "26호"],
            },
            {   idx: 3,
                name: "슈탠다드 양말_남녀 숏앵클 10팩",
                img: "men/ac/socks/item_4",
                sumimg2: "men/ac/socks/sum2/item_4",
                sumimg3: "men/ac/socks/sum3/item_4",
                oprice: "17900",
                dprice: "13900",
                review: "34", 
                color: ["Black", "Gray"],
                size: ["24호", "26호"],
            },
            {   idx: 4,
                name: "[슈탠다드] 쿠션 골지 크루 5팩",
                img: "men/ac/socks/item_5",
                sumimg2: "men/ac/socks/sum2/item_5",
                sumimg3: "men/ac/socks/sum3/item_5",
                oprice: "12900",
                dprice: "9900",
                review: "13", 
                color: ["Black", "Gray"],
                size: ["24호", "26호"],
            },
            {   idx: 5,
                name: "슈탠다드 양말_남성 쇼트 무지 7팩",
                img: "men/ac/socks/item_6",
                sumimg2: "men/ac/socks/sum2/item_6",
                sumimg3: "men/ac/socks/sum3/item_6",
                oprice: "10000",
                dprice: "7900",
                review: "81", 
                color: ["Black", "Gray"],
                size: ["24호", "26호"],
            },
            {   idx: 6,
                name: "남성 요일 페이크삭스 7팩",
                img: "men/ac/socks/item_7",
                sumimg2: "men/ac/socks/sum2/item_7",
                sumimg3: "men/ac/socks/sum3/item_7",
                oprice: "10000",
                dprice: "7900",
                review: "102", 
                color: ["Black", "Gray"],
                size: ["24호", "26호"],
            },
            {   idx: 7,
                name: "슈탠다드 스포츠 크루 2팩",
                img: "men/ac/socks/item_8",
                sumimg2: "men/ac/socks/sum2/item_8",
                sumimg3: "men/ac/socks/sum3/item_8",
                oprice: "10000",
                dprice: "7900",
                review: "53", 
                color: ["Black", "Gray"],
                size: ["24호", "26호"],
            },
        ],
        // 3-2. 모자
        "모자": [
            {   idx: 0,
                name: "나일론 와이드 버킷햇",
                img: "men/ac/hats/item_1",
                sumimg2: "men/ac/hats/sum2/item_1",
                sumimg3: "men/ac/hats/sum3/item_1",
                oprice: "29900",
                dprice: "19900",
                review: "19",
                color: ["Black", "Ivory", "Blue"],
                size: ["FREE"],
            },
            {   idx: 1,
                name: "무지 코튼 라운드 버킷햇",
                img: "men/ac/hats/item_2",
                sumimg2: "men/ac/hats/sum2/item_2",
                sumimg3: "men/ac/hats/sum3/item_2",
                oprice: "29900",
                dprice: "19900",
                review: "44",
                color: ["Black", "Ivory", "Light Blue", "Hunter"],
                size: ["FREE"],
            },
            {   idx: 2,
                name: "[캠프 네이쳐] 유틸리티 스포티즘 볼캡",
                img: "men/ac/hats/item_3",
                sumimg2: "men/ac/hats/sum2/item_3",
                sumimg3: "men/ac/hats/sum3/item_3",
                oprice: "25900",
                dprice: "19900",
                review: "19",
                color: ["Black", "Beige", "Khaki", "Orange"],
                size: ["FREE"],
            },
            {   idx: 3,
                name: "아일렛 베이직 버킷햇",
                img: "men/ac/hats/item_4",
                sumimg2: "men/ac/hats/sum2/item_4",
                sumimg3: "men/ac/hats/sum3/item_4",
                oprice: "19900",
                dprice: "11900",
                review: "44",
                color: ["Black", "Beige", "Khaki", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 4,
                name: "투톤 베이직 볼캡",
                img: "men/ac/hats/item_5",
                sumimg2: "men/ac/hats/sum2/item_5",
                sumimg3: "men/ac/hats/sum3/item_5",
                oprice: "10000",
                dprice: "7900",
                review: "19",
                color: ["White", "Red", "Yellow"],
                size: ["FREE"],
            },
            {   idx: 5,
                name: "무지 볼캡",
                img: "men/ac/hats/item_6",
                sumimg2: "men/ac/hats/sum2/item_6",
                sumimg3: "men/ac/hats/sum3/item_6",
                oprice: "19900",
                dprice: "9900",
                review: "44",
                color: ["White", "Black", "Gray", "Beige", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 6,
                name: "STND 헤링본 버킷햇",
                img: "men/ac/hats/item_7",
                sumimg2: "men/ac/hats/sum2/item_7",
                sumimg3: "men/ac/hats/sum3/item_7",
                oprice: "29900",
                dprice: "18630",
                review: "19",
                color: ["White", "Black", "Khaki"],
                size: ["FREE"],
            },
            {   idx: 7,
                name: "소프트 6족 무지 볼캡",
                img: "men/ac/hats/item_8",
                sumimg2: "men/ac/hats/sum2/item_8",
                sumimg3: "men/ac/hats/sum3/item_8",
                oprice: "10000",
                dprice: "7900",
                review: "44",
                color: ["White", "Black", "Beige", "Yellow", "Blue"],
                size: ["FREE"],
            },
            {   idx: 8,
                name: "STND 버킷햇",
                img: "men/ac/hats/item_9",
                sumimg2: "men/ac/hats/sum2/item_9",
                sumimg3: "men/ac/hats/sum3/item_9",
                oprice: "29900",
                dprice: "17900",
                review: "19",
                color: ["Black", "Beige", "Khaki", "Navy"],
                size: ["FREE"],
            },
            {   idx: 9,
                name: "STND 트윌 버킷햇",
                img: "men/ac/hats/item_10",
                sumimg2: "men/ac/hats/sum2/item_10",
                sumimg3: "men/ac/hats/sum3/item_10",
                oprice: "29900",
                dprice: "17900",
                review: "44",
                color: ["Black", "Light Beige", "Khaki", "Cream"],
                size: ["FREE"],
            },
            {   idx: 10,
                name: "LA 필기체 볼캡",
                img: "men/ac/hats/item_11",
                sumimg2: "men/ac/hats/sum2/item_1",
                sumimg3: "men/ac/hats/sum3/item_1",
                oprice: "19900",
                dprice: "11900",
                review: "44",
                color: ["White", "Black", "Yellow", "Beige", "Green"],
                size: ["FREE"],
            },
        ],
    },
};

export default menData;
