// new/best 페이지 상품 데이터
const prdData = {
    // 1. new 상품 데이터
    "new": {
        "women": [
            {   idx: 0,
                name: "케이블 삭스",
                img: "women/new/item_1",
                sumimg2: "women/best/sum2/item_8",
                sumimg3: "women/best/sum3/item_8",
                oprice: "",
                dprice: "3900",
                review: "42", 
            },
            {   idx: 1,
                name: "[경량EVA] 더블스트랩 리커버리 슬리퍼",
                img: "women/new/item_2",
                sumimg2: "women/best/sum2/item_16",
                sumimg3: "women/best/sum3/item_16",
                oprice: "25900",
                dprice: "24900",
                review: "17", 
            },
            {   idx: 2,
                name: "[캠프 네이쳐] 유틸리티 스포티즘 볼캡",
                img: "women/new/item_4",
                sumimg2: "men/ac/hats/sum2/item_3",
                sumimg3: "men/ac/hats/sum3/item_3",
                oprice: "25900",
                dprice: "24900",
                review: "53", 
            },
            {   idx: 3,
                name: "스퀘어 미디엄 숄더백",
                img: "women/new/item_5",
                sumimg2: "women/new/sum2/item_1",
                sumimg3: "women/new/sum3/item_1",
                oprice: "29900",
                dprice: "27900",
                review: "4", 
            },
            {   idx: 4,
                name: "미니 스퀘어 크로스백",
                img: "women/new/item_6",
                sumimg2: "women/new/sum2/item_2",
                sumimg3: "women/new/sum3/item_2",
                oprice: "39900",
                dprice: "36900",
                review: "20", 
            },
            {   idx: 5,
                name: "스퀘어 미니 토트백",
                img: "women/new/item_7",
                sumimg2: "women/new/sum2/item_3",
                sumimg3: "women/new/sum3/item_3",
                oprice: "29900",
                dprice: "27900",
                review: "21", 
            },
            {   idx: 6,
                name: "화섬 포켓 백팩",
                img: "women/new/item_8",
                sumimg2: "women/new/sum2/item_4",
                sumimg3: "women/new/sum3/item_4",
                oprice: "39900",
                dprice: "36900",
                review: "22", 
            },
            {   idx: 7,
                name: "청키 트랙솔 메리제인 5.0",
                img: "women/new/item_9",
                sumimg2: "women/new/sum2/item_5",
                sumimg3: "women/new/sum3/item_5",
                oprice: "49900",
                dprice: "46900",
                review: "23", 
            },
            {   idx: 8,
                name: "오버솔 와이드 4CM 리프트 스니커즈",
                img: "women/new/item_10",
                sumimg2: "women/new/sum2/item_6",
                sumimg3: "women/new/sum3/item_6",
                oprice: "39900",
                dprice: "36900",
                review: "24", 
            },
            {   idx: 9,
                name: "스퀘어 가보시 힐 샌들",
                img: "women/new/item_11",
                sumimg2: "women/new/sum2/item_7",
                sumimg3: "women/new/sum3/item_7",
                oprice: "",
                dprice: "39900",
                review: "", 
            },
            {   idx: 10,
                name: "벨트 스트랩 클로그 뮬 3.5",
                img: "women/new/item_12",
                sumimg2: "women/new/sum2/item_8",
                sumimg3: "women/new/sum3/item_8",
                oprice: "49900",
                dprice: "46900",
                review: "26", 
            },
            {   idx: 11,
                name: "스퀘어 리본 투웨이 샌들",
                img: "women/new/item_13",
                sumimg2: "women/new/sum2/item_9",
                sumimg3: "women/new/sum3/item_9",
                oprice: "39900",
                dprice: "36900",
                review: "27", 
            },
            {   idx: 12,
                name: "[고프코어] 스카치 트랙 스니커즈",
                img: "women/new/item_14",
                sumimg2: "women/new/sum2/item_10",
                sumimg3: "women/new/sum3/item_10",
                oprice: "49900",
                dprice: "46900",
                review: "28", 
            },
            {   idx: 13,
                name: "패딩 스트랩 샌들",
                img: "women/new/item_15",
                sumimg2: "women/new/sum2/item_11",
                sumimg3: "women/new/sum3/item_11",
                oprice: "",
                dprice: "35900",
                review: "29", 
            },
            {   idx: 14,
                name: "슬림 컵솔 스니커즈",
                img: "women/new/item_16",
                sumimg2: "women/new/sum2/item_12",
                sumimg3: "women/new/sum3/item_12",
                oprice: "39900",
                dprice: "36900",
                review: "7", 
            },
        ],
        "men": [
            {   idx: 15,
                name: "나일론 스트링 백팩",
                img: "men/new/item_2",
                sumimg2: "women/best/sum2/item_18",
                sumimg3: "women/best/sum3/item_18",
                oprice: "39900",
                dprice: "30320",
                review: "3", 
            },
            {   idx: 16,
                name: "빈티지 레터링 볼캡",
                img: "men/new/item_3",
                sumimg2: "women/best/sum2/item_19",
                sumimg3: "women/best/sum3/item_19",
                oprice: "25900",
                dprice: "23900",
                review: "4", 
            },
            {   idx: 17,
                name: "[시누 PICK] 오솔라이트 유니 레더 독일군",
                img: "men/new/item_4",
                sumimg2: "men/shoes/sneakers/sum2/item_3",
                sumimg3: "men/shoes/sneakers/sum3/item_3",
                oprice: "59900",
                dprice: "45520",
                review: "5", 
            },
            {   idx: 18,
                name: "베이직 코트화",
                img: "men/new/item_5",
                sumimg2: "women/best/sum2/item_20",
                sumimg3: "women/best/sum3/item_20",
                oprice: "59900",
                dprice: "56900",
                review: "6", 
            },
            {   idx: 19,
                name: "[오솔라이트] 유니레더 NEW ARMY 독일군 스니커즈 4.5cm키높이",
                img: "men/new/item_6",
                sumimg2: "women/best/sum2/item_21",
                sumimg3: "women/best/sum3/item_21",
                oprice: "59900",
                dprice: "45520",
                review: "7", 
            },
            {   idx: 20,
                name: "[에어쿠션] 초경량 논슬립 슬립온 워킹화",
                img: "men/new/item_7",
                sumimg2: "women/best/sum2/item_22",
                sumimg3: "women/best/sum3/item_22",
                oprice: "39900",
                dprice: "37900",
                review: "8", 
            },
            {   idx: 21,
                name: "소프트 슬림 베이직 스니커즈",
                img: "men/new/item_8",
                sumimg2: "men/shoes/sneakers/sum2/item_8",
                sumimg3: "men/shoes/sneakers/sum3/item_8",
                oprice: "59900",
                dprice: "29900",
                review: "9", 
            },
            {   idx: 22,
                name: "[경량EVA] 아웃도어 투 벨크로 샌들",
                img: "men/new/item_9",
                sumimg2: "women/shoes/sandal/sum2/item_5",
                sumimg3: "women/shoes/sandal/sum3/item_5",
                oprice: "39900",
                dprice: "29900",
                review: "10", 
            },
            {   idx: 23,
                name: "오버솔 스니커즈",
                img: "men/new/item_10",
                sumimg2: "women/new/sum2/item_13",
                sumimg3: "women/new/sum3/item_13",
                oprice: "49900",
                dprice: "46900",
                review: "11", 
            },
            {   idx: 24,
                name: "크로스 스트랩 슬라이드",
                img: "men/new/item_11",
                sumimg2: "men/shoes/slippers/sum2/item_8",
                sumimg3: "men/shoes/slippers/sum3/item_8",
                oprice: "",
                dprice: "19900",
                review: "15900", 
            },
            {   idx: 25,
                name: "무지 코튼 라운드 버킷햇",
                img: "men/new/item_13",
                sumimg2: "men/ac/hats/sum2/item_2",
                sumimg3: "men/ac/hats/sum3/item_2",
                oprice: "29900",
                dprice: "19900",
                review: "32", 
            },
            {   idx: 26,
                name: "[경량EVA] 어글리 리커버리 쪼리",
                img: "men/new/item_14",
                sumimg2: "men/shoes/slippers/sum2/item_9",
                sumimg3: "men/shoes/slippers/sum3/item_9",
                oprice: "29900",
                dprice: "14900",
                review: "43", 
            },
            {   idx: 27,
                name: "[경량EVA] 논슬립 베이직 리커버리 쪼리",
                img: "men/new/item_15",
                sumimg2: "men/shoes/slippers/sum2/item_3",
                sumimg3: "men/shoes/slippers/sum3/item_3",
                oprice: "",
                dprice: "15900",
                review: "5", 
            },
            {   idx: 28,
                name: "슈펜 X 비슬로우 리커버리 슬라이더",
                img: "men/new/item_16",
                sumimg2: "men/shoes/slippers/sum2/item_6",
                sumimg3: "men/shoes/slippers/sum3/item_6",
                oprice: "19900",
                dprice: "9900",
                review: "53", 
            },
        ],
        "kids": [
            {   idx: 29,
                name: "[FW신상] 키즈 부클자수 피치 볼캡",
                img: "kids/new/item_1",
                sumimg2: "women/best/sum2/item_26",
                sumimg3: "women/best/sum3/item_26",
                oprice: "19900",
                dprice: "16110",
                review: "2", 
            },
            {   idx: 30,
                name: "[FW신상] 키즈 베이직 컬러 테슬 로퍼",
                img: "kids/new/item_2",
                sumimg2: "women/new/sum2/item_14",
                sumimg3: "women/new/sum3/item_14",
                oprice: "29900",
                dprice: "24210",
                review: "3", 
            },
            {   idx: 31,
                name: "[FW신상] 키즈 글리터 리본 쿠션 플랫",
                img: "kids/new/item_3",
                sumimg2: "women/new/sum2/item_15",
                sumimg3: "women/new/sum3/item_15",
                oprice: "25900",
                dprice: "21510",
                review: "5", 
            },
            {   idx: 32,
                name: "[FW신상] 키즈 독일군 스니커즈",
                img: "kids/new/item_4",
                sumimg2: "women/new/sum2/item_16",
                sumimg3: "women/new/sum3/item_16",
                oprice: "39900",
                dprice: "32310",
                review: "5", 
            },
            {   idx: 33,
                name: "[FW신상] 키즈 메리제인 샤이닝 플랫 구두",
                img: "kids/new/item_5",
                sumimg2: "kids/shoes/shoe/sum2/item_9",
                sumimg3: "kids/shoes/shoe/sum3/item_9",
                oprice: "25900",
                dprice: "21510",
                review: "6", 
            },
            {   idx: 34,
                name: "[FW신상] 키즈 메리제인 버튼 플랫",
                img: "kids/new/item_6",
                sumimg2: "women/new/sum2/item_17",
                sumimg3: "women/new/sum3/item_17",
                oprice: "25900",
                dprice: "21510",
                review: "7", 
            },
            {   idx: 35,
                name: "[FW신상] 플랫폼 스트랩 구두",
                img: "kids/new/item_7",
                sumimg2: "women/best/sum2/item_27",
                sumimg3: "women/best/sum3/item_27",
                oprice: "39900",
                dprice: "33210",
                review: "8", 
            },
            {   idx: 36,
                name: "[FW신상] [연주회] 키즈 리본 연주회 구두",
                img: "kids/new/item_8",
                sumimg2: "kids/shoes/shoe/sum2/item_10",
                sumimg3: "kids/shoes/shoe/sum3/item_10",
                oprice: "39900",
                dprice: "33210",
                review: "9", 
            },
            {   idx: 37,
                name: "[FW신상] [연주회] 키즈 주얼 벨벳 플랫구두",
                img: "kids/new/item_9",
                sumimg2: "women/new/sum2/item_18",
                sumimg3: "women/new/sum3/item_18",
                oprice: "39900",
                dprice: "33210",
                review: "10", 
            },
            {   idx: 38,
                name: "[테디아일랜드] 키즈 모카신",
                img: "kids/new/item_10",
                sumimg2: "women/new/sum2/item_19",
                sumimg3: "women/new/sum3/item_19",
                oprice: "39900",
                dprice: "35900",
                review: "11", 
            },
            {   idx: 39,
                name: "[레인보우] 키즈 그래픽 밸크로 실내화",
                img: "kids/new/item_11",
                sumimg2: "women/new/sum2/item_20",
                sumimg3: "women/new/sum3/item_20",
                oprice: "12900",
                dprice: "9900",
                review: "12", 
            },
            {   idx: 40,
                name: "[FW신상] 키즈 컬러블록 캠프캡",
                img: "kids/new/item_12",
                sumimg2: "women/new/sum2/item_21",
                sumimg3: "women/new/sum3/item_21",
                oprice: "25900",
                dprice: "21510",
                review: "13", 
            },
            {   idx: 41,
                name: "키즈 컬러 체크 우산",
                img: "kids/new/item_13",
                sumimg2: "women/best/sum2/item_28",
                sumimg3: "women/best/sum3/item_28",
                oprice: "19900",
                dprice: "15900",
                review: "14", 
            },
            {   idx: 42,
                name: "키즈 피셔맨 말랑 젤리샌들",
                img: "kids/new/item_14",
                sumimg2: "women/new/sum2/item_22",
                sumimg3: "women/new/sum3/item_22",
                oprice: "19900",
                dprice: "14900",
                review: "15", 
            },
            {   idx: 43,
                name: "키즈 경량 리커버리 샌들",
                img: "kids/new/item_15",
                sumimg2: "women/best/sum2/item_29",
                sumimg3: "women/best/sum3/item_29",
                oprice: "29900",
                dprice: "15210",
                review: "16", 
            },
            {   idx: 44,
                name: "키즈 첼시 레인부츠",
                img: "kids/new/item_16",
                sumimg2: "women/new/sum2/item_23",
                sumimg3: "women/new/sum3/item_23",
                oprice: "29900",
                dprice: "17910",
                review: "", 
            },
        ]
    },
    // 2. best 상품 데이터
    "best": {
        "women": [
            {   idx: 0,
                name: "[시누 PICK] 경량EVA 논슬립 베이직 리커버리 쪼리",
                img: "women/best/item_1",
                sumimg2: "men/shoes/slippers/sum2/item_3",
                sumimg3: "men/shoes/slippers/sum3/item_3",
                oprice: "19900",
                dprice: "15900",
                review: "2", 
            },
            {   idx: 1,
                name: "리본 포인트 슬라이드 1.0",
                img: "women/best/item_2",
                sumimg2: "women/best/sum2/item_2",
                sumimg3: "women/best/sum3/item_2",
                oprice: "39900",
                dprice: "29900",
                review: "3", 
            },
            {   idx: 2,
                name: "[테니스클럽] 베이직 덱 스니커즈 (듀얼쿠션)",
                img: "women/best/item_3",
                sumimg2: "women/best/sum2/item_3",
                sumimg3: "women/best/sum3/item_3",
                oprice: "29900",
                dprice: "19900",
                review: "4", 
            },
            {   idx: 3,
                name: "청키 트랙솔 버클 로퍼 4.0",
                img: "women/best/item_4",
                sumimg2: "women/best/sum2/item_4",
                sumimg3: "women/best/sum3/item_4",
                oprice: "49900",
                dprice: "44900",
                review: "5", 
            },
            {   idx: 4,
                name: "소프트 퀼팅백",
                img: "women/best/item_5",
                sumimg2: "women/best/sum2/item_5",
                sumimg3: "women/best/sum3/item_5",
                oprice: "49900",
                dprice: "39900",
                review: "6", 
            },
            {   idx: 5,
                name: "[라이트] 청키 리프트 뮬 스니커즈 (버진폼)",
                img: "women/best/item_6",
                sumimg2: "women/best/sum2/item_6",
                sumimg3: "women/best/sum3/item_6",
                oprice: "39900",
                dprice: "29900",
                review: "7", 
            },
            {   idx: 6,
                name: "베이직 스트랩 샌들 1.5",
                img: "women/best/item_7",
                sumimg2: "women/shoes/sandal/sum2/item_7",
                sumimg3: "women/shoes/sandal/sum3/item_7",
                oprice: "29900",
                dprice: "19900",
                review: "8", 
            },
            {   idx: 7,
                name: "✔MD 추천✔ 소프트 미니 퀼팅백",
                img: "women/best/item_8",
                sumimg2: "women/best/sum2/item_7",
                sumimg3: "women/best/sum3/item_7",
                oprice: "39900",
                dprice: "29900",
                review: "9", 
            },
            {   idx: 8,
                name: "케이블 삭스",
                img: "women/best/item_9",
                sumimg2: "women/best/sum2/item_8",
                sumimg3: "women/best/sum3/item_8",
                oprice: "",
                dprice: "3900",
                review: "10", 
            },
            {   idx: 9,
                name: "패딩 플랫폼 쪼리 슬리퍼",
                img: "women/best/item_10",
                sumimg2: "women/best/sum2/item_9",
                sumimg3: "women/best/sum3/item_9",
                oprice: "39900",
                dprice: "29900",
                review: "11", 
            },
            {   idx: 10,
                name: "라운드 투스트랩 밴딩 슬라이드 1.0",
                img: "women/best/item_11",
                sumimg2: "women/best/sum2/item_10",
                sumimg3: "women/best/sum3/item_10",
                oprice: "19900",
                dprice: "9900",
                review: "12", 
            },
            {   idx: 11,
                name: "캔버스 쇼퍼백",
                img: "women/best/item_12",
                sumimg2: "women/best/sum2/item_11",
                sumimg3: "women/best/sum3/item_11",
                oprice: "39900",
                dprice: "25900",
                review: "13", 
            },
            {   idx: 12,
                name: "스트링 에코백",
                img: "women/best/item_13",
                sumimg2: "women/best/sum2/item_12",
                sumimg3: "women/best/sum3/item_12",
                oprice: "19900",
                dprice: "15900",
                review: "14", 
            },
            {   idx: 13,
                name: "패딩 덮개 뮬 샌들 3.0 ",
                img: "women/best/item_14",
                sumimg2: "women/best/sum2/item_13",
                sumimg3: "women/best/sum3/item_13",
                oprice: "39900",
                dprice: "19900",
                review: "15", 
            },
        ],
        "men": [
            {   idx: 14,
                name: "[시누 PICK] 오솔라이트 유니 레더 독일군",
                img: "men/best/item_1",
                sumimg2: "men/shoes/sneakers/sum2/item_3",
                sumimg3: "men/shoes/sneakers/sum3/item_3",
                oprice: "59900",
                dprice: "45520",
                review: "2", 
            },
            {   idx: 15,
                name: "마하그리드 스트링 백팩",
                img: "men/best/item_3",
                sumimg2: "women/best/sum2/item_14",
                sumimg3: "women/best/sum3/item_14",
                oprice: "59900",
                dprice: "39900",
                review: "4", 
            },
            {   idx: 16,
                name: "남성 경량 베이직 더비",
                img: "men/best/item_4",
                sumimg2: "women/best/sum2/item_15",
                sumimg3: "women/best/sum3/item_15",
                oprice: "79900",
                dprice: "75900",
                review: "5", 
            },
            {   idx: 17,
                name: "[경량EVA] 더블스트랩 리커버리 슬리퍼",
                img: "men/best/item_5",
                sumimg2: "women/best/sum2/item_16",
                sumimg3: "women/best/sum3/item_16",
                oprice: "25900",
                dprice: "24900",
                review: "6", 
            },
            {   idx: 18,
                name: "[콜라보왕 깡스] 21클래식 레더로퍼",
                img: "men/best/item_6",
                sumimg2: "women/best/sum2/item_17",
                sumimg3: "women/best/sum3/item_17",
                oprice: "109000",
                dprice: "65900",
                review: "7", 
            },
            {   idx: 19,
                name: "[무료교환/무료반품] 나일론 스트링 백팩",
                img: "men/best/item_7",
                sumimg2: "women/best/sum2/item_18",
                sumimg3: "women/best/sum3/item_18",
                oprice: "39900",
                dprice: "30320",
                review: "8", 
            },
            {   idx: 20,
                name: "빈티지 레터링 볼캡",
                img: "men/best/item_8",
                sumimg2: "women/best/sum2/item_19",
                sumimg3: "women/best/sum3/item_19",
                oprice: "25900",
                dprice: "23900",
                review: "9", 
            },
            {   idx: 21,
                name: "베이직 코트화",
                img: "men/best/item_9",
                sumimg2: "women/best/sum2/item_20",
                sumimg3: "women/best/sum3/item_20",
                oprice: "59900",
                dprice: "56900",
                review: "10", 
            },
            {   idx: 22,
                name: "[오솔라이트] 유니레더 NEW ARMY 독일군 스니커즈 4.5cm키높이",
                img: "men/best/item_10",
                sumimg2: "women/best/sum2/item_21",
                sumimg3: "women/best/sum3/item_21",
                oprice: "59900",
                dprice: "45520",
                review: "11", 
            },
            {   idx: 23,
                name: "[에어쿠션] 초경량 논슬립 슬립온 워킹화",
                img: "men/best/item_11",
                sumimg2: "women/best/sum2/item_22",
                sumimg3: "women/best/sum3/item_22",
                oprice: "39900",
                dprice: "37900",
                review: "12", 
            },
            {   idx: 24,
                name: "소프트 슬림 베이직 스니커즈",
                img: "men/best/item_12",
                sumimg2: "men/shoes/sneakers/sum2/item_8",
                sumimg3: "men/shoes/sneakers/sum3/item_8",
                oprice: "59900",
                dprice: "29900",
                review: "13", 
            },
            {   idx: 25,
                name: "[캠프 네이쳐] 유틸리티 스포티즘 볼캡",
                img: "men/best/item_13",
                sumimg2: "men/ac/hats/sum2/item_3",
                sumimg3: "men/ac/hats/sum3/item_3",
                oprice: "25900",
                dprice: "19900",
                review: "14", 
            },
            {   idx: 26,
                name: "[경량EVA] 어글리 리커버리 쪼리",
                img: "men/best/item_14",
                sumimg2: "men/shoes/slippers/sum2/item_9",
                sumimg3: "men/shoes/slippers/sum3/item_9",
                oprice: "29900",
                dprice: "14900",
                review: "15", 
            },
            {   idx: 27,
                name: "[경량EVA] 플로우 리커버리 클로그",
                img: "men/best/item_15",
                sumimg2: "men/shoes/slippers/sum2/item_10",
                sumimg3: "men/shoes/slippers/sum3/item_10",
                oprice: "35900",
                dprice: "25900",
                review: "16", 
            },
            {   idx: 28,
                name: "네이비 3M 스트링 백팩",
                img: "men/best/item_16",
                sumimg2: "women/bag/backpack/sum2/item_4",
                sumimg3: "women/bag/backpack/sum3/item_4",
                oprice: "59900",
                dprice: "35900",
                review: "", 
            },

        ],
        "kids": [
            {   idx: 29,
                name: "[레인보우] 키즈 그라데이션 우의",
                img: "kids/best/item_1",
                sumimg2: "women/best/sum2/item_23",
                sumimg3: "women/best/sum3/item_23",
                oprice: "49900",
                dprice: "38610",
                review: "2", 
            },
            {   idx: 30,
                name: "[레인보우] 하트윙 또각 굽구두",
                img: "kids/best/item_2",
                sumimg2: "women/best/sum2/item_24",
                sumimg3: "women/best/sum3/item_24",
                oprice: "39900",
                dprice: "29900",
                review: "3", 
            },
            {   idx: 31,
                name: "[레인보우] 키즈 베이직 밸크로 실내화",
                img: "kids/best/item_3",
                sumimg2: "women/best/sum2/item_25",
                sumimg3: "women/best/sum3/item_25",
                oprice: "12900",
                dprice: "9900",
                review: "4", 
            },
            {   idx: 32,
                name: "[FW신상] 키즈 부클자수 피치 볼캡",
                img: "kids/best/item_4",
                sumimg2: "women/best/sum2/item_26",
                sumimg3: "women/best/sum3/item_26",
                oprice: "19900",
                dprice: "16110",
                review: "5", 
            },
            {   idx: 33,
                name: "[FW신상] 플랫폼 스트랩 구두",
                img: "kids/best/item_5",
                sumimg2: "women/best/sum2/item_27",
                sumimg3: "women/best/sum3/item_27",
                oprice: "39900",
                dprice: "33210",
                review: "6", 
            },
            {   idx: 34,
                name: "키즈 컬러 체크 우산",
                img: "kids/best/item_6",
                sumimg2: "women/best/sum2/item_28",
                sumimg3: "women/best/sum3/item_28",
                oprice: "19900",
                dprice: "15900",
                review: "7", 
            },
            {   idx: 35,
                name: "키즈 경량 리커버리 샌들",
                img: "kids/best/item_7",
                sumimg2: "women/best/sum2/item_29",
                sumimg3: "women/best/sum3/item_29",
                oprice: "29900",
                dprice: "15210",
                review: "8", 
            },
            {   idx: 36,
                name: "키즈 메쉬 버킷햇",
                img: "kids/best/item_8",
                sumimg2: "kids/ac/hats/sum2/item_1",
                sumimg3: "kids/ac/hats/sum3/item_1",
                oprice: "29900",
                dprice: "17910",
                review: "9", 
            },
            {   idx: 37,
                name: "키즈 메쉬 플랩캡",
                img: "kids/best/item_9",
                sumimg2: "kids/ac/hats/sum2/item_2",
                sumimg3: "kids/ac/hats/sum3/item_2",
                oprice: "29900",
                dprice: "21510",
                review: "10", 
            },
            {   idx: 38,
                name: "[테디아일랜드] 키즈 양말 4족 세트",
                img: "kids/best/item_10",
                sumimg2: "kids/ac/socks/sum2/item_11",
                sumimg3: "kids/ac/socks/sum3/item_11",
                oprice: "15900",
                dprice: "13410",
                review: "11", 
            },
            {   idx: 39,
                name: "키즈 경량 EVA 샌들",
                img: "kids/best/item_11",
                sumimg2: "women/best/sum2/item_30",
                sumimg3: "women/best/sum3/item_30",
                oprice: "25900",
                dprice: "11610",
                review: "12", 
            },
            {   idx: 40,
                name: "키즈 플랫폼 베이직 샌들",
                img: "kids/best/item_12",
                sumimg2: "women/best/sum2/item_31",
                sumimg3: "women/best/sum3/item_31",
                oprice: "29900",
                dprice: "17910",
                review: "13", 
            },
            {   idx: 41,
                name: "키즈 스트라이프 스니커즈 5족 세트",
                img: "kids/best/item_13",
                sumimg2: "kids/ac/socks/sum2/item_15",
                sumimg3: "kids/ac/socks/sum3/item_15",
                oprice: "9900",
                dprice: "8010",
                review: "14", 
            },
            {   idx: 42,
                name: "키즈 메리제인 쿠션플랫",
                img: "kids/best/item_14",
                sumimg2: "kids/shoes/shoe/sum2/item_2",
                sumimg3: "kids/shoes/shoe/sum3/item_2",
                oprice: "29900",
                dprice: "11610",
                review: "15", 
            },
            {   idx: 43,
                name: "키즈 그라데이션 슬리퍼",
                img: "kids/best/item_15",
                sumimg2: "kids/shoes/sandal/sum2/item_13",
                sumimg3: "kids/shoes/sandal/sum3/item_13",
                oprice: "19900",
                dprice: "8010",
                review: "16", 
            },
            {   idx: 44,
                name: "키즈 핫픽스 레이스 양말 3족 세트",
                img: "kids/best/item_16",
                sumimg2: "women/best/sum2/item_32",
                sumimg3: "women/best/sum3/item_32",
                oprice: "9900",
                dprice: "8010",
                review: "", 
            },
        ]
    }
};

export default prdData;