// 여성 더미데이터 - wommenData.js
const womenData = {
    // 1. 신발데이터
    shoes: {
        // 1-1. 플랫슈즈
        "플랫슈즈": [
            {   idx: 0,
                name:"🌟TOP 5 [가드너] 스윗버튼 메리제인 플랫 1.0",
                img: "women/shoes/flat/item_1",
                wsimg: "women/shoes/flat/item_1",
                sumimg2: "flat/sum2/item_1",
                sumimg3: "flat/sum3/item_1",
                oprice: "29900",
                dprice: "28900",
                review: "170",
                color: ["Black", "Light Pink", "Light Yellow", "Ivory", "Light Green"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 1,
                name:"트윙클 발레리나 플랫 1.0",
                img: "women/shoes/flat/item_2",
                wsimg: "women/shoes/flat/item_2",
                sumimg2: "flat/sum2/item_2",
                sumimg3: "flat/sum3/item_2",
                oprice: "35900",
                dprice: "33900",
                review: "63",
                color: ["White", "Black", "Dark Red", "Pink", "Light Yellow"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 2,
                name:"[가드너] 스퀘어 리본 플랫슈즈",
                img: "women/shoes/flat/item_3",
                wsimg: "women/shoes/flat/item_3",
                sumimg2: "flat/sum2/item_3",
                sumimg3: "flat/sum3/item_3",
                oprice: "25900",
                dprice: "24900",
                review: "3",
                color: ["White", "Black", "Yellow", "Light Beige", "Light Green"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 3,
                name:"와이드 라운드 버클 단화 2.0",
                img: "women/shoes/flat/item_4",
                wsimg: "women/shoes/flat/item_4",
                sumimg2: "flat/sum2/item_4",
                sumimg3: "flat/sum3/item_4",
                oprice: "39900",
                dprice: "37900",
                review: "29",
                color: ["Black", "Yellow", "Brown"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 4,
                name:"베이직 메리제인 플랫 1.0",
                img: "women/shoes/flat/item_5",
                wsimg: "women/shoes/flat/item_5",
                sumimg2: "flat/sum2/item_5",
                sumimg3: "flat/sum3/item_5",
                oprice: "19900",
                dprice: "14880",
                review: "129",
                color: ["Camel", "Black", "Light Pink", "Light Beige", "Ivory"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 5,
                name:"발레리나 메리제인 플랫",
                img: "women/shoes/flat/item_6",
                wsimg: "women/shoes/flat/item_6",
                sumimg2: "flat/sum2/item_6",
                sumimg3: "flat/sum3/item_6",
                oprice: "39900",
                dprice: "37900",
                review: "6",
                color: ["Black", "Pink", "Beige", "Silver"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 6,
                name:"오블리크 V컷 플랫",
                img: "women/shoes/flat/item_7",
                wsimg: "women/shoes/flat/item_7",
                sumimg2: "flat/sum2/item_7",
                sumimg3: "flat/sum3/item_7",
                oprice: "29900",
                dprice: "27900",
                review: "13",
                color: ["White", "Black", "Yellow", "Beige", "Brown"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 7,
                name:"쿠션 플랫 1.0",
                img: "women/shoes/flat/item_8",
                wsimg: "women/shoes/flat/item_8",
                sumimg2: "flat/sum2/item_8",
                sumimg3: "flat/sum3/item_8",
                oprice: "15900",
                dprice: "12380",
                review: "103",
                color: ["Light Gray", "Black", "Red", "Pink", "Indian Pink", "Lemon", "Graish Blue", "Mint Green"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 8,
                name:"스퀘어 밴딩 바부슈 플랫 1.0",
                img: "women/shoes/flat/item_9",
                wsimg: "women/shoes/flat/item_9",
                sumimg2: "flat/sum2/item_9",
                sumimg3: "flat/sum3/item_9",
                oprice: "19900",
                dprice: "14880",
                review: "43",
                color: ["Black", "Pink", "Red", "Pink", "Indian Pink", "Burgandy", "Green", "Light Green", "Ivory"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 9,
                name:"[가드너] 스퀘어 메리제인 플랫슈즈",
                img: "women/shoes/flat/item_10",
                wsimg: "women/shoes/flat/item_10",
                sumimg2: "flat/sum2/item_10",
                sumimg3: "flat/sum3/item_10",
                oprice: "29900",
                dprice: "27900",
                review: "7",
                color: ["White", "Black", "Light Green", "Light Blue", "Light Coral", "Light Violet", "Light Beige"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 10,
                name:"슈블리 메리제인 플랫",
                img: "women/shoes/flat/item_11",
                wsimg: "women/shoes/flat/item_11",
                sumimg2: "flat/sum2/item_11",
                sumimg3: "flat/sum3/item_11",
                oprice: "39900",
                dprice: "23630",
                review: "25",
                color: ["White", "Black", "Brown", "Chocolate", "Beige", "Light Green"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 11,
                name:"메리제인 웰트 플랫 1.0",
                img: "women/shoes/flat/item_12",
                wsimg: "women/shoes/flat/item_12",
                sumimg2: "flat/sum2/item_12",
                sumimg3: "flat/sum3/item_12",
                oprice: "29900",
                dprice: "22900",
                review: "13",
                color: ["Black", "Pink", "Light Blue", "Ivory"],
                size: ["225", "230", "235", "240", "245", "250", "255"],
            },
            {   idx: 12,
                name:"메리제인 발레슈 단화 1.0",
                img: "women/shoes/flat/item_13",
                wsimg: "women/shoes/flat/item_13",
                sumimg2: "flat/sum2/item_13",
                sumimg3: "flat/sum3/item_13",
                oprice: "39900",
                dprice: "37900",
                review: "17",
                color: ["Black", "Yellow", "Ivory"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 13,
                name:"와이드 라운드 메리제인 단화 2.0",
                img: "women/shoes/flat/item_14",
                wsimg: "women/shoes/flat/item_14",
                sumimg2: "flat/sum2/item_14",
                sumimg3: "flat/sum3/item_14",
                oprice: "39900",
                dprice: "37900",
                review: "2",
                color: ["Black", "Ivory", "Brown"],
                size: ["230", "235", "240", "245", "250"],

            },
        ],
        // 1-2. 샌들
        "샌들": [
            {   idx: 0,
                name:"스퀘어 투스트랩 샌들 5.0",
                img:"women/shoes/sandal/item_1",
                wsimg: "women/shoes/sandal/item_1",
                sumimg2: "sandal/sum2/item_1",
                sumimg3: "sandal/sum3/item_1",
                oprice:"39900",
                dprice:"29900",
                review:"5",
                color: ["White", "Black", "Beige", "Light Green", "Orange"],
                size: ["230", "235", "240", "245", "250"],
            },
            {   idx: 1,
                name:"플랫폼 피셔맨 샌들 3.5",
                img:"women/shoes/sandal/item_2",
                wsimg: "women/shoes/sandal/item_2",
                sumimg2: "sandal/sum2/item_2",
                sumimg3: "sandal/sum3/item_2",
                oprice:"39900",
                dprice:"35910",
                review:"33",
                color: ["Black", "Ivory", "Brown"],
                size: ["230", "240", "250"],
            },
            {   idx: 2,
                name:"와이드 플랫 피셔맨 샌들 1.0",
                img:"women/shoes/sandal/item_3",
                wsimg: "women/shoes/sandal/item_3",
                sumimg2: "sandal/sum2/item_3",
                sumimg3: "sandal/sum3/item_3",
                oprice:"39900",
                dprice:"35910",
                review:"26",
                color: ["White", "Black", "Light Yellow", "Dark Beige", "Lavender"],
                size: ["230", "240", "250"],
            },
            {   idx: 3,
                name:"[도영도영이 PICK] 라운드 커버 단화샌들 1.0",
                img:"women/shoes/sandal/item_4",
                wsimg: "women/shoes/sandal/item_4",
                sumimg2: "sandal/sum2/item_4",
                sumimg3: "sandal/sum3/item_4",
                oprice:"29900",
                dprice:"26910",
                review:"89",
                color: ["White", "Black", "Brown"],
                size: ["230", "240", "250"],
            },
            {   idx: 4,
                name:"[경량EVA] 아웃도어 투 벨크로 샌들",
                img:"women/shoes/sandal/item_5",
                wsimg: "women/shoes/sandal/item_5",
                sumimg2: "sandal/sum2/item_5",
                sumimg3: "sandal/sum3/item_5",
                oprice:"39900",
                dprice:"37900",
                review:"1",
                color: ["Black", "Light Beige", "Ivory"],
                size: ["230", "240", "250", "260", "270"],
            },
            {   idx: 5,
                name:"리커버리 소프트 젤리샌들",
                img:"women/shoes/sandal/item_6",
                wsimg: "women/shoes/sandal/item_6",
                sumimg2: "sandal/sum2/item_6",
                sumimg3: "sandal/sum3/item_6",
                oprice:"19900",
                dprice:"17910",
                review:"",
                color: ["Black", "Purple", "Two_tone"],
                size: ["230", "240", "250"],
            },
            {   idx: 6,
                name:"베이직 스트랩 샌들 1.5",
                img:"women/shoes/sandal/item_7",
                wsimg: "women/shoes/sandal/item_7",
                sumimg2: "sandal/sum2/item_7",
                sumimg3: "sandal/sum3/item_7",
                oprice:"19900",
                dprice:"9900",
                review:"44",
                color: ["White", "Black", "Beige", "Brown"],
                size: ["230", "240", "250"],
            },
            {   idx: 7,
                name:"사선 스트랩 쪼리 젤리 샌들 1.0",
                img:"women/shoes/sandal/item_8",
                wsimg: "women/shoes/sandal/item_8",
                sumimg2: "sandal/sum2/item_8",
                sumimg3: "sandal/sum3/item_8",
                oprice:"39900",
                dprice:"29900",
                review:"51",
                color: ["Black", "Ivory", "Silver"],
                size: ["230", "240", "250"],
            },
            {   idx: 8,
                name:"멀티 스트랩 플랫폼 샌들",
                img:"women/shoes/sandal/item_9",
                wsimg: "women/shoes/sandal/item_9",
                sumimg2: "sandal/sum2/item_9",
                sumimg3: "sandal/sum3/item_9",
                oprice:"39900",
                dprice:"19900",
                review:"101",
                color: ["White", "Black", "Blue", "Silver"],
                size: ["230", "240", "250"],
            },
            {   idx: 9,
                name:"에스파듀 패턴 슬라이드 2.0",
                img:"women/shoes/sandal/item_10",
                wsimg: "women/shoes/sandal/item_10",
                sumimg2: "sandal/sum2/item_10",
                sumimg3: "sandal/sum3/item_10",
                oprice:"39900",
                dprice:"23630",
                review:"7",
                color: ["White", "Black", "Indian Pink", "Pale Green"],
                size: ["230", "240", "250"],
            },
            {   idx: 10,
                name:"어글리 스포티 샌들",
                img:"women/shoes/sandal/item_11",
                wsimg: "women/shoes/sandal/item_11",
                sumimg2: "sandal/sum2/item_11",
                sumimg3: "sandal/sum3/item_11",
                oprice:"39900",
                dprice:"23630",
                review:"35",
                color: ["Black", "Khaki"],
                size: ["230", "240", "250"],
            },
            {   idx: 11,
                name:"3-스트랩 스포티 샌들",
                img:"women/shoes/sandal/item_12",
                wsimg: "women/shoes/sandal/item_12",
                sumimg2: "sandal/sum2/item_12",
                sumimg3: "sandal/sum3/item_12",
                oprice:"39900",
                dprice:"19900",
                review:"41",
                color: ["Black", "Beige"],
                size: ["230", "240", "250"],
            },
        ],
    },
    // 2. 가방데이터
    bag: {
        // 2-1. 백팩
        "백팩": [
            {   idx: 0,
                name:"[테디아일랜드] 베이직 백팩",
                img:"women/bag/backpack/item_1",
                wsimg: "women/bag/backpack/item_1",
                sumimg2: "backpack/sum2/item_1",
                sumimg3: "backpack/sum3/item_1",
                oprice:"29900",
                dprice:"27900",
                review:"23",
                color: ["Black", "Ivory", "Lavender"],
                size: ["FREE"],
            },
            {   idx: 1,
                name:"나일론 라운드 백팩",
                img:"women/bag/backpack/item_2",
                wsimg: "women/bag/backpack/item_2",
                sumimg2: "backpack/sum2/item_2",
                sumimg3: "backpack/sum3/item_2",
                oprice:"39900",
                dprice:"37900",
                review:"101",
                color: ["Black", "Cream"],
                size: ["FREE"],
            },
            {   idx: 2,
                name:"마하 그리드 로고 베이직 백팩",
                img:"women/bag/backpack/item_3",
                wsimg: "women/bag/backpack/item_3",
                sumimg2: "backpack/sum2/item_3",
                sumimg3: "backpack/sum3/item_3",
                oprice:"29900",
                dprice:"18630",
                review:"51",
                color: ["Black", "Beige", "Khaki"],
                size: ["FREE"],
            },
            {   idx: 3,
                name:"네이비 3M 스트링 백팩",
                img:"women/bag/backpack/item_4",
                wsimg: "women/bag/backpack/item_4",
                sumimg2: "backpack/sum2/item_4",
                sumimg3: "backpack/sum3/item_4",
                oprice:"59900",
                dprice:"55900",
                review:"38",
                color: ["Black"],
                size: ["FREE"],
            },
            {   idx: 4,
                name:"[테디아일랜드] 멀티 매쉬 백팩",
                img:"women/bag/backpack/item_5",
                wsimg: "women/bag/backpack/item_5",
                sumimg2: "backpack/sum2/item_5",
                sumimg3: "backpack/sum3/item_5",
                oprice:"59900",
                dprice:"55900",
                review:"16",
                color: ["Black", "Ivory", "Lavender"],
                size: ["FREE"],
            },
        ],
        // 2-2. 미니백
        "미니백": [
            {   idx: 0,
                name:"🌟재입고🌟 나일론 셔링 미니백",
                img:"women/bag/minibag/item_1",
                wsimg: "women/bag/minibag/item_1",
                sumimg2: "minibag/sum2/item_1",
                sumimg3: "minibag/sum3/item_1",
                oprice:"25900",
                dprice:"19900",
                review:"83",
                color: ["Black", "Ivory", "Light Purple", "Mint"],
                size: ["FREE"],
            },
            {   idx: 1,
                name:"🌟뉴컬러🌟 [버블 폼폼] 링클 미니 호보백",
                img:"women/bag/minibag/item_2",
                wsimg: "women/bag/minibag/item_2",
                sumimg2: "minibag/sum2/item_2",
                sumimg3: "minibag/sum3/item_2",
                oprice:"29900",
                dprice:"25900",
                review:"9",
                color: ["Black", "Light Yellow", "Ivory", "Violet"],
                size: ["FREE"],
            },
            {   idx: 2,
                name:"[버블 폼폼] 링클 미니 체인 크로스백",
                img:"women/bag/minibag/item_3",
                wsimg: "women/bag/minibag/item_3",
                sumimg2: "minibag/sum2/item_3",
                sumimg3: "minibag/sum3/item_3",
                oprice:"25900",
                dprice:"23900",
                review:"15",
                color: ["Black", "Light Yellow", "Ivory", "Violet"],
                size: ["FREE"],
            },
            {   idx: 3,
                name:"마하 그리드 베이직 사코슈백",
                img:"women/bag/minibag/item_4",
                wsimg: "women/bag/minibag/item_4",
                sumimg2: "minibag/sum2/item_4",
                sumimg3: "minibag/sum3/item_4",
                oprice:"25900",
                dprice:"18630",
                review:"34",
                color: ["White", "Black", "Beige"],
                size: ["FREE"],
            },
            {   idx: 4,
                name:"네트 핸드폰 백",
                img:"women/bag/minibag/item_5",
                wsimg: "women/bag/minibag/item_5",
                sumimg2: "minibag/sum2/item_5",
                sumimg3: "minibag/sum3/item_5",
                oprice:"19900",
                dprice:"14880",
                review:"69",
                color: ["Orange", "Yellow", "Green", "Light Green", "Blue"],
                size: ["FREE"],
            },
            {   idx: 5,
                name:"캐스퍼 백인백",
                img:"women/bag/minibag/item_6",
                wsimg: "women/bag/minibag/item_6",
                sumimg2: "minibag/sum2/item_6",
                sumimg3: "minibag/sum3/item_6",
                oprice:"15900",
                dprice:"14880",
                review:"38",
                color: ["Black", "Pink", "Beige", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 6,
                name:"가벼운 스트링 핸드폰백",
                img:"women/bag/minibag/item_7",
                wsimg: "women/bag/minibag/item_7",
                sumimg2: "minibag/sum2/item_7",
                sumimg3: "minibag/sum3/item_7",
                oprice:"19900",
                dprice:"14880",
                review:"23",
                color: ["Black", "Khaki"],
                size: ["FREE"],
            },
            {   idx: 7,
                name:"뉴반달 S",
                img:"women/bag/minibag/item_8",
                wsimg: "women/bag/minibag/item_8",
                sumimg2: "minibag/sum2/item_8",
                sumimg3: "minibag/sum3/item_8",
                oprice:"35900",
                dprice:"22380",
                review:"14",
                color: ["Black", "Ivory", "Yellow", "Brown"],
                size: ["FREE"],
            },
            {   idx: 8,
                name:"[NAVY] 베이직 와펜 핸드폰 가방",
                img:"women/bag/minibag/item_9",
                wsimg: "women/bag/minibag/item_9",
                sumimg2: "minibag/sum2/item_9",
                sumimg3: "minibag/sum3/item_9",
                oprice:"19900",
                dprice:"15900",
                review:"462",
                color: ["Black", "Ivory", "Violet"],
                size: ["FREE"],
            },
            {   idx: 9,
                name:"패턴 미니백",
                img:"women/bag/minibag/item_10",
                wsimg: "women/bag/minibag/item_10",
                sumimg2: "minibag/sum2/item_10",
                sumimg3: "minibag/sum3/item_10",
                oprice:"15900",
                dprice:"14880",
                review:"33",
                color: ["Black", "Red", "Beige", "Lavender", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 10,
                name:"핸들 스퀘어",
                img:"women/bag/minibag/item_11",
                wsimg: "women/bag/minibag/item_11",
                sumimg2: "minibag/sum2/item_11",
                sumimg3: "minibag/sum3/item_11",
                oprice:"29900",
                dprice:"18630",
                review:"13",
                color: ["White", "Black", "Light Pink", "Beige"],
                size: ["FREE"],
            },
            {   idx: 11,
                name:"미니스퀘어",
                img:"women/bag/minibag/item_12",
                wsimg: "women/bag/minibag/item_12",
                sumimg2: "minibag/sum2/item_12",
                sumimg3: "minibag/sum3/item_12",
                oprice:"29900",
                dprice:"18630",
                review:"45",
                color: ["Black", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 12,
                name:"슬림 미니백",
                img:"women/bag/minibag/item_13",
                wsimg: "women/bag/minibag/item_13",
                sumimg2: "minibag/sum2/item_13",
                sumimg3: "minibag/sum3/item_13",
                oprice:"29900",
                dprice:"18630",
                review:"54",
                color: ["Black", "Light Yellow", "Ivory", "Green", "Brown"],
                size: ["FREE"],
            },
            {   idx: 13,
                name:"바게트 미니백",
                img:"women/bag/minibag/item_14",
                wsimg: "women/bag/minibag/item_14",
                sumimg2: "minibag/sum2/item_14",
                sumimg3: "minibag/sum3/item_14",
                oprice:"39900",
                dprice:"23630",
                review:"42",
                color: ["Black", "Ivory", "Brown"],
                size: ["FREE"],
            },
            {   idx: 14,
                name:"슈펜 베이직 핸드폰 가방",
                img:"women/bag/minibag/item_15",
                wsimg: "women/bag/minibag/item_15",
                sumimg2: "minibag/sum2/item_15",
                sumimg3: "minibag/sum3/item_15",
                oprice:"15900",
                dprice:"14880",
                review:"56",
                color: ["Gray", "Black", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 15,
                name:"에코 미니 토트백",
                img:"women/bag/minibag/item_16",
                wsimg: "women/bag/minibag/item_16",
                sumimg2: "minibag/sum2/item_16",
                sumimg3: "minibag/sum3/item_16",
                oprice:"15900",
                dprice:"14880",
                review:"23",
                color: ["Charcoal", "White", "Light Violet", "Pale Green"],
                size: ["FREE"],
            },
            {   idx: 16,
                name:"클래식 미니백",
                img:"women/bag/minibag/item_17",
                wsimg: "women/bag/minibag/item_17",
                sumimg2: "minibag/sum2/item_17",
                sumimg3: "minibag/sum3/item_17",
                oprice:"49900",
                dprice:"28630",
                review:"64",
                color: ["Black", "Ivory", "Light Blue", "Brown"],
                size: ["FREE"],
            },
            {   idx: 17,
                name:"린넨 미니백",
                img:"women/bag/minibag/item_18",
                wsimg: "women/bag/minibag/item_18",
                sumimg2: "minibag/sum2/item_18",
                sumimg3: "minibag/sum3/item_18",
                oprice:"19900",
                dprice:"14880",
                review:"32",
                color: ["Cream", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 18,
                name:"CHEWY MINIBAG",
                img:"women/bag/minibag/item_19",
                wsimg: "women/bag/minibag/item_19",
                sumimg2: "minibag/sum2/item_19",
                sumimg3: "minibag/sum3/item_19",
                oprice:"15900",
                dprice:"14880",
                review:"53",
                color: ["Black", "Light Pink", "Light Blue", "Navy"],
                size: ["FREE"],
            },
        ],

    },
    // 3. 잡화데이터
    ac: {
        // 3-1. 양말
        "양말": [
            {   idx: 0,
                name:"슈탠다드 양말 남녀 하프삭스 7팩",
                img:"women/ac/socks/item_1",
                wsimg: "women/ac/socks/item_1",
                sumimg2: "socks/sum2/item_1",
                sumimg3: "socks/sum3/item_1",
                oprice:"17900",
                dprice:"17380",
                review:"65",
                color: ["White", "Black", "Two_tone"],
                size: ["24호", "26호"],
            },
            {   idx: 1,
                name:"[슈탠다드] 남녀공용 5팩 페이크 삭스 (라이트웨이트)",
                img:"women/ac/socks/item_2",
                wsimg: "women/ac/socks/item_2",
                sumimg2: "socks/sum2/item_2",
                sumimg3: "socks/sum3/item_2",
                oprice:"9900",
                dprice:"5900",
                review:"3",
                color: ["White", "Black", "Gray", "Light Gray", "Beige", "Mix"],
                size: ["24호", "26호"],
            },
            {   idx: 2,
                name:"여성 골지 니삭스",
                img:"women/ac/socks/item_3",
                wsimg: "women/ac/socks/item_3",
                sumimg2: "socks/sum2/item_3",
                sumimg3: "socks/sum3/item_3",
                oprice:"",
                dprice:"12900",
                review:"55",
                color: ["White", "Black", "Charcoal"],
                size: ["24호", "26호"],
            },
            {   idx: 3,
                name:"슈탠다드 무지 크루 삭스 5팩",
                img:"women/ac/socks/item_4",
                wsimg: "women/ac/socks/item_4",
                sumimg2: "socks/sum2/item_4",
                sumimg3: "socks/sum3/item_4",
                oprice:"",
                dprice:"12380",
                review:"25",
                color: ["White", "Black", "Gray", "Two_tone"],
                size: ["24호", "26호"],
            },
            {   idx: 4,
                name:"슈탠다드 미들 삭스 5팩",
                img:"women/ac/socks/item_5",
                wsimg: "women/ac/socks/item_5",
                sumimg2: "socks/sum2/item_5",
                sumimg3: "socks/sum3/item_5",
                oprice:"12900",
                dprice:"12380",
                review:"25",
                color: ["White", "Black", "Two_tone"],
                size: ["24호", "26호"],
            },
            {   idx: 5,
                name:"슈탠다드 양말_남녀 숏앵클 10팩",
                img:"women/ac/socks/item_6",
                wsimg: "women/ac/socks/item_6",
                sumimg2: "socks/sum2/item_6",
                sumimg3: "socks/sum3/item_6",
                oprice:"17900",
                dprice:"17380",
                review:"63",
                color: ["White", "Black", "Two_tone"],
                size: ["24호", "26호"],
            },
            {   idx: 6,
                name:"망고컬러 쇼트 삭스",
                img:"women/ac/socks/item_7",
                wsimg: "women/ac/socks/item_7",
                sumimg2: "socks/sum2/item_7",
                sumimg3: "socks/sum3/item_7",
                oprice:"",
                dprice:"3900",
                review:"13",
                color: ["White", "Black", "Gray", "Oatmeal Melange"],
                size: ["24호", "26호"],
            },
            {   idx: 7,
                name:"여성 베이직 니삭스",
                img:"women/ac/socks/item_8",
                wsimg: "women/ac/socks/item_8",
                sumimg2: "socks/sum2/item_8",
                sumimg3: "socks/sum3/item_8",
                oprice:"",
                dprice:"7900",
                review:"42",
                color: ["White", "Black", "Charcoal"],
                size: ["24호", "26호"],
            },
        ],
         // 3-2. 모자
        "모자": [
            {   idx: 0,
                name:"배색 포인트 니트 버킷햇",
                img:"women/ac/hats/item_1",
                wsimg: "women/ac/hats/item_1",
                sumimg2: "hats/sum2/item_1",
                sumimg3: "hats/sum3/item_1",
                oprice:"29900",
                dprice:"19900",
                review:"7",
                color: ["Black", "Light Beige", "Ivory"],
                size: ["FREE"],
            },
            {   idx: 1,
                name:"페이퍼 블렌디드 선캡",
                img:"women/ac/hats/item_2",
                wsimg: "women/ac/hats/item_2",
                sumimg2: "hats/sum2/item_2",
                sumimg3: "hats/sum3/item_2",
                oprice:"19900",
                dprice:"15900",
                review:"32",
                color: ["Black", "Light Pink", "Light Beige"],
                size: ["FREE"],
            },
            {   idx: 2,
                name:"쿨면 내추럴 하드 버킷햇",
                img:"women/ac/hats/item_3",
                wsimg: "women/ac/hats/item_3",
                sumimg2: "hats/sum2/item_3",
                sumimg3: "hats/sum3/item_3",
                oprice:"29900",
                dprice:"19900",
                review:"51",
                color: ["Black", "Beige", "Ivory", "Blue"],
                size: ["FREE"],
            },
            {   idx: 3,
                name:"[캠프 네이쳐] 유틸리티 스포티즘 볼캡",
                img:"women/ac/hats/item_4",
                wsimg: "women/ac/hats/item_4",
                sumimg2: "hats/sum2/item_4",
                sumimg3: "hats/sum3/item_4",
                oprice:"25900",
                dprice:"19900",
                review:"53",
                color: ["Black", "Beige", "Khaki", "Orange"],
                size: ["FREE"],
            },
            {   idx: 4,
                name:"코튼 블렌드 케이블 버킷햇",
                img:"women/ac/hats/item_5",
                wsimg: "women/ac/hats/item_5",
                sumimg2: "hats/sum2/item_5",
                sumimg3: "hats/sum3/item_5",
                oprice:"29900",
                dprice:"19900",
                review:"40",
                color: ["Black", "Light Beige", "Ivory", "Violet"],
                size: ["FREE"],
            },
            {   idx: 5,
                name:"화섬 베이직 버킷햇 2",
                img:"women/ac/hats/item_6",
                wsimg: "women/ac/hats/item_6",
                sumimg2: "hats/sum2/item_6",
                sumimg3: "hats/sum3/item_6",
                oprice:"15900",
                dprice:"12900",
                review:"3",
                color: ["White", "Black", "Red", "Beige", "Purple"],
                size: ["FREE"],
            },
            {   idx: 6,
                name:"투톤 베이직 볼캡",
                img:"women/ac/hats/item_7",
                wsimg: "women/ac/hats/item_7",
                sumimg2: "hats/sum2/item_7",
                sumimg3: "hats/sum3/item_7",
                oprice:"10000",
                dprice:"9380",
                review:"11",
                color: ["White", "Black", "Gray", "Red", "Pink"],
                size: ["FREE"],
            },
        ],

    },
}

export default womenData;