// 아동 더미데이터 - kidsData.js
const kidsData = {
    // 1. 신발데이터
    shoes: {
        // 1-1. 구두
        "구두": [
            {   idx: 0,
                name: "[레인보우] 레이스 토오픈 라이팅 구두",
                img: "shoes/shoe/item_1",
                wsimg: "kids/shoes/shoe/item_1",
                sumimg2: "shoe/sum2/item_1",
                sumimg3: "shoe/sum3/item_1",
                oprice: "39900",
                dprice: "29900",
                review: "32",
                color: ["Pink", "Purple"],
                size: ["160", "170", "180", "190", "200", "210"],
            },
            {   idx: 1,
                name: "키즈 메리제인 쿠션플랫",
                img: "shoes/shoe/item_2",
                wsimg: "kids/shoes/shoe/item_2",
                sumimg2: "shoe/sum2/item_2",
                sumimg3: "shoe/sum3/item_2",
                oprice: "29900",
                dprice: "15900",
                review: "76",
                color: ["Black", "Light Pink", "Yellow", "Lavender"],
                size: ["160", "170", "180", "190", "200", "210"],
            },
            {   idx: 2,
                name: "신데렐라 유리구두 (라이팅)",
                img: "shoes/shoe/item_3",
                wsimg: "kids/shoes/shoe/item_3",
                sumimg2: "shoe/sum2/item_3",
                sumimg3: "shoe/sum3/item_3",
                oprice: "49900",
                dprice: "23900",
                review: "30",
                color: ["Blue", "Lavender"],
                size: ["150", "160", "170", "180", "190", "200"],
            },
            {   idx: 3,
                name: "[레인보우] 키즈 리본 쿠션 플랫",
                img: "shoes/shoe/item_4",
                wsimg: "kids/shoes/shoe/item_4",
                sumimg2: "shoe/sum2/item_4",
                sumimg3: "shoe/sum3/item_4",
                oprice: "19900",
                dprice: "17900",
                review: "53",
                color: ["Black"],
                size: ["150", "160", "170", "180", "190", "200", "210", "220"],
            },
            {   idx: 4,
                name: "키즈 니트 쿠션플랫",
                img: "shoes/shoe/item_5",
                wsimg: "kids/shoes/shoe/item_5",
                sumimg2: "shoe/sum2/item_5",
                sumimg3: "shoe/sum3/item_5",
                oprice: "19900",
                dprice: "15900",
                review: "201",
                color: ["Black", "Ivory", "Purple"],
                size: ["150", "160", "170", "180", "190", "200", "210"],
            },
            {   idx: 5,
                name: "[레인보우] 리본 쿠션 플랫",
                img: "shoes/shoe/item_6",
                wsimg: "kids/shoes/shoe/item_6",
                sumimg2: "shoe/sum2/item_6",
                sumimg3: "shoe/sum3/item_6",
                oprice: "19900",
                dprice: "17900",
                review: "11",
                color: ["Black", "Red", "Pink", "Light Pink", "Light Yellow"],
                size: ["150", "160", "170", "180", "190", "200", "210"],
            },
            {   idx: 6,
                name: "[연주회] 키즈 주얼 연주회 구두",
                img: "shoes/shoe/item_7",
                wsimg: "kids/shoes/shoe/item_7",
                sumimg2: "shoe/sum2/item_7",
                sumimg3: "shoe/sum3/item_7",
                oprice: "39900",
                dprice: "29900",
                review: "4",
                color: ["White", "Black", "Purple"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 7,
                name: "키즈 연주회구두",
                img: "shoes/shoe/item_8",
                wsimg: "kids/shoes/shoe/item_8",
                sumimg2: "shoe/sum2/item_8",
                sumimg3: "shoe/sum3/item_8",
                oprice: "29900",
                dprice: "14900",
                review: "2",
                color: ["White", "Black"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 8,
                name: "키즈 메리제인 샤이닝 플랫 구두",
                img: "shoes/shoe/item_9",
                wsimg: "kids/shoes/shoe/item_9",
                sumimg2: "shoe/sum2/item_9",
                sumimg3: "shoe/sum3/item_9",
                oprice: "39900",
                dprice: "25900",
                review: "42",
                color: ["Black", "Burgundy"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 9,
                name: "[연주회] 키즈 리본 연주회 구두",
                img: "shoes/shoe/item_10",
                wsimg: "kids/shoes/shoe/item_10",
                sumimg2: "shoe/sum2/item_10",
                sumimg3: "shoe/sum3/item_10",
                oprice: "39900",
                dprice: "29900",
                review: "53",
                color: ["White", "Black", "Red"],
                size: ["170", "180", "190", "200", "210"],
            },
        ],
        // 1-2. 샌들
        "샌들": [
            {   idx: 0,
                name: "슈펜키즈 지그재그 샌들",
                img: "shoes/sandal/item_1",
                wsimg: "kids/shoes/sandal/item_1",
                sumimg2: "sandal/sum2/item_1",
                sumimg3: "sandal/sum3/item_1",
                oprice: "29900",
                dprice: "19900",
                review: "103",
                color: ["Black", "Ivory", "Green", "Orange"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 1,
                name: "[레인보우] 또각굽 공주샌들",
                img: "shoes/sandal/item_2",
                wsimg: "kids/shoes/sandal/item_2",
                sumimg2: "sandal/sum2/item_2",
                sumimg3: "sandal/sum3/item_2",
                oprice: "19900",
                dprice: "15900",
                review: "66",
                color: ["Black", "Pink", "Beige", "Orange"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 2,
                name: "DRP드롭X룸슈즈",
                img: "shoes/sandal/item_3",
                wsimg: "kids/shoes/sandal/item_3",
                sumimg2: "sandal/sum2/item_3",
                sumimg3: "sandal/sum3/item_3",
                oprice: "15900",
                dprice: "9900",
                review: "13",
                color: ["Red", "Yelow", "Green"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 3,
                name: "키즈 유니콘 쿠션샌들",
                img: "shoes/sandal/item_4",
                wsimg: "kids/shoes/sandal/item_4",
                sumimg2: "sandal/sum2/item_4",
                sumimg3: "sandal/sum3/item_4",
                oprice: "29900",
                dprice: "17900",
                review: "43",
                color: ["Ligth Pink", "Coral", "Purple"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 4,
                name: "키즈 썸머 스트랩 쿠션 샌들",
                img: "shoes/sandal/item_5",
                wsimg: "kids/shoes/sandal/item_5",
                sumimg2: "sandal/sum2/item_5",
                sumimg3: "sandal/sum3/item_5",
                oprice: "29900",
                dprice: "17900",
                review: "19",
                color: ["White", "Camel", "Black", "Brown"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 5,
                name: "키즈 버클 EVA 샌들",
                img: "shoes/sandal/item_6",
                wsimg: "kids/shoes/sandal/item_6",
                sumimg2: "sandal/sum2/item_6",
                sumimg3: "sandal/sum3/item_6",
                oprice: "29900",
                dprice: "19900",
                review: "14",
                color: ["Black", "Pink", "Ivory", "Brown", "Lavender"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 6,
                name: "피셔맨 쿠션샌들",
                img: "shoes/sandal/item_7",
                wsimg: "kids/shoes/sandal/item_7",
                sumimg2: "sandal/sum2/item_7",
                sumimg3: "sandal/sum3/item_7",
                oprice: "25900",
                dprice: "20720",
                review: "5",
                color: ["Brown", "Navy"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 7,
                name: "슈펜키즈 EVA 샌들",
                img: "shoes/sandal/item_8",
                wsimg: "kids/shoes/sandal/item_8",
                sumimg2: "sandal/sum2/item_8",
                sumimg3: "sandal/sum3/item_8",
                oprice: "19900",
                dprice: "11900",
                review: "204",
                color: ["Pink", "Navy"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 8,
                name: "[레인보우] 퐁퐁 리본 공주샌들",
                img: "shoes/sandal/item_9",
                wsimg: "kids/shoes/sandal/item_9",
                sumimg2: "sandal/sum2/item_9",
                sumimg3: "sandal/sum3/item_9",
                oprice: "39900",
                dprice: "29900",
                review: "53",
                color: ["White", "Light Pink", "Lavender"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 9,
                name: "키즈 크레용 버클 쿠션 샌들",
                img: "shoes/sandal/item_10",
                wsimg: "kids/shoes/sandal/item_10",
                sumimg2: "sandal/sum2/item_10",
                sumimg3: "sandal/sum3/item_10",
                oprice: "29900",
                dprice: "19900",
                review: "57",
                color: ["White", "Green", "Orange", "Brown"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 10,
                name: "키즈 리커버리 슬리퍼",
                img: "shoes/sandal/item_11",
                wsimg: "kids/shoes/sandal/item_11",
                sumimg2: "sandal/sum2/item_11",
                sumimg3: "sandal/sum3/item_11",
                oprice: "15900",
                dprice: "9900",
                review: "61",
                color: ["Black", "Pink", "Yellow", "Ivory"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 11,
                name: "신비 아파트 EVA 샌들",
                img: "shoes/sandal/item_12",
                wsimg: "kids/shoes/sandal/item_12",
                sumimg2: "sandal/sum2/item_12",
                sumimg3: "sandal/sum3/item_12",
                oprice: "12900",
                dprice: "8900",
                review: "3",
                color: ["Pink", "Navy"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 12,
                name: "키즈 그라데이션 슬리퍼",
                img: "shoes/sandal/item_13",
                wsimg: "kids/shoes/sandal/item_13",
                sumimg2: "sandal/sum2/item_13",
                sumimg3: "sandal/sum3/item_13",
                oprice: "19900",
                dprice: "9900",
                review: "75",
                color: ["Light Pink", "Lavender"],
                size: ["170", "180", "190", "200", "210"],
            },
            {   idx: 13,
                name: "키즈 와이드 리커버리 샌들",
                img: "shoes/sandal/item_14",
                wsimg: "kids/shoes/sandal/item_14",
                sumimg2: "sandal/sum2/item_14",
                sumimg3: "sandal/sum3/item_14",
                oprice: "29900",
                dprice: "19900",
                review: "10",
                color: ["Black", "Pink", "Beige", "Lavender"],
                size: ["170", "180", "190", "200", "210"],
            },
        ],
    },
    // 2. 가방데이터
    bag: {
        // 2-1. 슬리퍼가방
        "슬리퍼가방": [
            {   idx: 0,
                name: "[뉴스쿨] 키즈 크로스 신발주머니",
                img: "bag/slipperbag/item_1",
                wsimg: "kids/bag/slipperbag/item_1",
                sumimg2: "slipperbag/sum2/item_1",
                sumimg3: "slipperbag/sum3/item_1",
                oprice: "15900",
                dprice: "14310",
                review: "51",
                color: ["Black", "Light Pink", "Violet"],
                size: ["FREE"],
            },
            {   idx: 1,
                name: "[뉴스쿨] 키즈 베이직 신발주머니",
                img: "bag/slipperbag/item_2",
                wsimg: "kids/bag/slipperbag/item_2",
                sumimg2: "slipperbag/sum2/item_2",
                sumimg3: "slipperbag/sum3/item_2",
                oprice: "9900",
                dprice: "8900",
                review: "67",
                color: ["Black", "Violet"],
                size: ["FREE"],
            },
        ],
        // 2-2. 패션가방
        "패션가방": [
            {   idx: 0,
                name: "[뉴스쿨] 키즈 슬링백",
                img: "bag/stylebag/item_1",
                wsimg: "kids/bag/stylebag/item_1",
                sumimg2: "stylebag/sum2/item_1",
                sumimg3: "stylebag/sum3/item_1",
                oprice: "20900",
                dprice: "18810",
                review: "",
                color: ["Black", "Light Pink", "Violet"],
                size: ["FREE"],
            },
            {   idx: 1,
                name: "키즈 목걸이 지갑",
                img: "bag/stylebag/item_2",
                wsimg: "kids/bag/stylebag/item_2",
                sumimg2: "stylebag/sum2/item_2",
                sumimg3: "stylebag/sum3/item_2",
                oprice: "12900",
                dprice: "11610",
                review: "32",
                color: ["Black", "Violet"],
                size: ["FREE"],
            },
            {   idx: 2,
                name: "키즈 화섬 미니 크로스백",
                img: "bag/stylebag/item_3",
                wsimg: "kids/bag/stylebag/item_3",
                sumimg2: "stylebag/sum2/item_3",
                sumimg3: "stylebag/sum3/item_3",
                oprice: "25900",
                dprice: "19900",
                review: "24",
                color: ["Black", "Ivory", "Violet"],
                size: ["FREE"],
            },
            {   idx: 3,
                name: "[디즈니] 앨리스 하트 크로스백",
                img: "bag/stylebag/item_4",
                wsimg: "kids/bag/stylebag/item_4",
                sumimg2: "stylebag/sum2/item_4",
                sumimg3: "stylebag/sum3/item_4",
                oprice: "35900",
                dprice: "32900",
                review: "104",
                color: ["Violet"],
                size: ["FREE"],
            },
            {   idx: 4,
                name: "키즈 미니 크로스백",
                img: "bag/stylebag/item_5",
                wsimg: "kids/bag/stylebag/item_5",
                sumimg2: "stylebag/sum2/item_5",
                sumimg3: "stylebag/sum3/item_5",
                oprice: "25900",
                dprice: "19900",
                review: "4",
                color: ["Black", "Violet"],
                size: ["FREE"],
            },
            {   idx: 5,
                name: "[슈펜키즈] 유니콘 목걸이 지갑",
                img: "bag/stylebag/item_6",
                wsimg: "kids/bag/stylebag/item_6",
                sumimg2: "stylebag/sum2/item_6",
                sumimg3: "stylebag/sum3/item_6",
                oprice: "9900",
                dprice: "7920",
                review: "83",
                color: ["Pink", "Green"],
                size: ["FREE"],
            },
            {   idx: 6,
                name: "겨울왕국 미니백",
                img: "bag/stylebag/item_7",
                wsimg: "kids/bag/stylebag/item_7",
                sumimg2: "stylebag/sum2/item_7",
                sumimg3: "stylebag/sum3/item_7",
                oprice: "39900",
                dprice: "31920",
                review: "13",
                color: ["Silver"],
                size: ["FREE"],
            },
            {   idx: 7,
                name: "미니마우스 미니백",
                img: "bag/stylebag/item_8",
                wsimg: "kids/bag/stylebag/item_8",
                sumimg2: "stylebag/sum2/item_8",
                sumimg3: "stylebag/sum3/item_8",
                oprice: "39900",
                dprice: "31920",
                review: "130",
                color: ["Black"],
                size: ["FREE"],
            },
            {   idx: 8,
                name: "겨울왕국 뽀글이 크로스백",
                img: "bag/stylebag/item_9",
                wsimg: "kids/bag/stylebag/item_9",
                sumimg2: "stylebag/sum2/item_9",
                sumimg3: "stylebag/sum3/item_9",
                oprice: "29900",
                dprice: "23920",
                review: "42",
                color: ["Lilac"],
                size: ["FREE"],
            },
        ],
    },
    // 3. 잡화데이터
    ac: {
        // 3-1. 양말
        "양말": [
            {   idx: 0,
                name: "키즈 체크 스포츠 양말 4족세트",
                img: "ac/socks/item_1",
                wsimg: "kids/ac/socks/item_1",
                sumimg2: "socks/sum2/item_1",
                sumimg3: "socks/sum3/item_1",
                oprice: "10900",
                dprice: "9810",
                review: "34",
                color: ["Pink", "Yellow", "Navy", "Lavender"],
                size: ["S", "M", "L"],
            },
            {   idx: 1,
                name: "키즈 스마일 스포츠 양말 4족 세트",
                img: "ac/socks/item_2",
                wsimg: "kids/ac/socks/item_2",
                sumimg2: "socks/sum2/item_2",
                sumimg3: "socks/sum3/item_2",
                oprice: "10900",
                dprice: "9810",
                review: "12",
                color: ["Black", "Red", "Green", "Navy", "Lavender"],
                size: ["S", "M", "L"],
            },
            {   idx: 2,
                name: "샤샤 레이스 양말",
                img: "ac/socks/item_3",
                wsimg: "kids/ac/socks/item_3",
                sumimg2: "socks/sum2/item_3",
                sumimg3: "socks/sum3/item_3",
                oprice: "",
                dprice: "5000",
                review: "13",
                color: ["White"],
                size: ["S", "M", "L"],
            },
            {   idx: 3,
                name: "키즈 골지 스트라이프 양말 4족세트",
                img: "ac/socks/item_4",
                wsimg: "kids/ac/socks/item_4",
                sumimg2: "socks/sum2/item_4",
                sumimg3: "socks/sum3/item_4",
                oprice: "12900",
                dprice: "11900",
                review: "49",
                color: ["Black", "Lavender"],
                size: ["S", "M", "L"],
            },
            {   idx: 4,
                name: "키즈 치즈 스니커즈 4족 세트",
                img: "ac/socks/item_5",
                wsimg: "kids/ac/socks/item_5",
                sumimg2: "socks/sum2/item_5",
                sumimg3: "socks/sum3/item_5",
                oprice: "9900",
                dprice: "8900",
                review: "103",
                color: ["Black", "Mix"],
                size: ["S", "M", "L"],
            },
            {   idx: 5,
                name: "키즈 프릴 니삭스 2족 세트",
                img: "ac/socks/item_6",
                wsimg: "kids/ac/socks/item_6",
                sumimg2: "socks/sum2/item_6",
                sumimg3: "socks/sum3/item_6",
                oprice: "9900",
                dprice: "8900",
                review: "13",
                color: ["White", "Pink"],
                size: ["S", "M", "L"],
            },
            {   idx: 6,
                name: "키즈 여아 패턴자수 양말 4족 세트",
                img: "ac/socks/item_7",
                wsimg: "kids/ac/socks/item_7",
                sumimg2: "socks/sum2/item_7",
                sumimg3: "socks/sum3/item_7",
                oprice: "12900",
                dprice: "11900",
                review: "7",
                color: ["Pink", "Lavender"],
                size: ["S", "M", "L"],
            },
            {   idx: 7,
                name: "스트라이프 니삭스",
                img: "ac/socks/item_8",
                wsimg: "kids/ac/socks/item_8",
                sumimg2: "socks/sum2/item_8",
                sumimg3: "socks/sum3/item_8",
                oprice: "10900",
                dprice: "5900",
                review: "63",
                color: ["Black"],
                size: ["S", "M", "L"],
            },
            {   idx: 8,
                name: "키즈 프릴 분리형 타이즈",
                img: "ac/socks/item_9",
                wsimg: "kids/ac/socks/item_9",
                sumimg2: "socks/sum2/item_9",
                sumimg3: "socks/sum3/item_9",
                oprice: "12900",
                dprice: "11900",
                review: "33",
                color: ["Pink", "Ivory"],
                size: ["S", "M", "L"],
            },
            {   idx: 9,
                name: "아동 베이직 5종 세트",
                img: "ac/socks/item_10",
                wsimg: "kids/ac/socks/item_10",
                sumimg2: "socks/sum2/item_10",
                sumimg3: "socks/sum3/item_10",
                oprice: "10000",
                dprice: "7900",
                review: "120",
                color: ["Gray", "Pink", "Yellow", "Black"],
                size: ["S", "M", "L"],
            },
            {   idx: 10,
                name: "[테디아일랜드] 키즈 양말 4족 세트",
                img: "ac/socks/item_11",
                wsimg: "kids/ac/socks/item_11",
                sumimg2: "socks/sum2/item_11",
                sumimg3: "socks/sum3/item_11",
                oprice: "15900",
                dprice: "14900",
                review: "15",
                color: ["Ivory"],
                size: ["S", "M", "L"],
            },
            {   idx: 11,
                name: "여아 유니콘 스니커즈 4족 세트",
                img: "ac/socks/item_12",
                wsimg: "kids/ac/socks/item_12",
                sumimg2: "socks/sum2/item_12",
                sumimg3: "socks/sum3/item_12",
                oprice: "9900",
                dprice: "8900",
                review: "5",
                color: ["Violet"],
                size: ["S", "M", "L"],
            },
            {   idx: 12,
                name: "키즈 스마일 스니커즈 4족 세트",
                img: "ac/socks/item_13",
                wsimg: "kids/ac/socks/item_13",
                sumimg2: "socks/sum2/item_13",
                sumimg3: "socks/sum3/item_13",
                oprice: "9900",
                dprice: "8900",
                review: "34",
                color: ["Black"],
                size: ["S", "M", "L"],
            },
            {   idx: 13,
                name: "키즈 스트라이프 덧신 5족 세트",
                img: "ac/socks/item_14",
                wsimg: "kids/ac/socks/item_14",
                sumimg2: "socks/sum2/item_14",
                sumimg3: "socks/sum3/item_14",
                oprice: "9900",
                dprice: "8900",
                review: "12",
                color: ["Black"],
                size: ["S", "M", "L"],
            },
            {   idx: 14,
                name: "키즈 스트라이프 스니커즈 5족 세트",
                img: "ac/socks/item_15",
                wsimg: "kids/ac/socks/item_15",
                sumimg2: "socks/sum2/item_15",
                sumimg3: "socks/sum3/item_15",
                oprice: "9900",
                dprice: "8900",
                review: "5",
                color: ["Black"],
                size: ["S", "M", "L"],
            },
        ],
        // 3-2. 모자
        "모자": [
            {   idx: 0,
                name: "키즈 메쉬 버킷햇",
                img: "ac/hats/item_1",
                wsimg: "kids/ac/hats/item_1",
                sumimg2: "hats/sum2/item_1",
                sumimg3: "hats/sum3/item_1",
                oprice: "29900",
                dprice: "25900",
                review: "",
                color: ["White", "Pink", "Purple"],
                size: ["FREE"],
            },
            {   idx: 1,
                name: "키즈 메쉬 플랩캡",
                img: "ac/hats/item_2",
                wsimg: "kids/ac/hats/item_2",
                sumimg2: "hats/sum2/item_2",
                sumimg3: "hats/sum3/item_2",
                oprice: "29900",
                dprice: "25900",
                review: "72",
                color: ["White", "Black", "Beige"],
                size: ["FREE"],
            },
            {   idx: 2,
                name: "키즈 리버서블 버킷햇",
                img: "ac/hats/item_3",
                wsimg: "kids/ac/hats/item_3",
                sumimg2: "hats/sum2/item_3",
                sumimg3: "hats/sum3/item_3",
                oprice: "29900",
                dprice: "25900",
                review: "",
                color: ["Black", "Ivory", "Violet"],
                size: ["FREE"],
            },
            {   idx: 3,
                name: "푸우 코듀로이 볼캡",
                img: "ac/hats/item_4",
                wsimg: "kids/ac/hats/item_4",
                sumimg2: "hats/sum2/item_4",
                sumimg3: "hats/sum3/item_4",
                oprice: "19900",
                dprice: "11900",
                review: "72",
                color: ["Pink", "Blue"],
                size: ["FREE"],
            },
            {   idx: 4,
                name: "키즈 썬캡",
                img: "ac/hats/item_5",
                wsimg: "kids/ac/hats/item_5",
                sumimg2: "hats/sum2/item_5",
                sumimg3: "hats/sum3/item_5",
                oprice: "25900",
                dprice: "15900",
                review: "",
                color: ["White", "Black", "Pink", "Purple"],
                size: ["FREE"],
            },
            {   idx: 5,
                name: "키즈 솔리드 볼캡",
                img: "ac/hats/item_6",
                wsimg: "kids/ac/hats/item_6",
                sumimg2: "hats/sum2/item_6",
                sumimg3: "hats/sum3/item_6",
                oprice: "19900",
                dprice: "15900",
                review: "72",
                color: ["Black", "Ivory", "Purple"],
                size: ["FREE"],
            },
            {   idx: 6,
                name: "[테니스클럽] 키즈 배색 볼캡",
                img: "ac/hats/item_7",
                wsimg: "kids/ac/hats/item_7",
                sumimg2: "hats/sum2/item_7",
                sumimg3: "hats/sum3/item_7",
                oprice: "19900",
                dprice: "15900",
                review: "",
                color: ["Red", "Green", "Navy"],
                size: ["FREE"],
            },
            {   idx: 7,
                name: "베이직 비니",
                img: "ac/hats/item_8",
                wsimg: "kids/ac/hats/item_8",
                sumimg2: "hats/sum2/item_8",
                sumimg3: "hats/sum3/item_8",
                oprice: "",
                dprice: "12900",
                review: "72",
                color: ["Black", "Green"],
                size: ["FREE"],
            },
            {   idx: 8,
                name: "트윈 폼폼 비니",
                img: "ac/hats/item_9",
                wsimg: "kids/ac/hats/item_9",
                sumimg2: "hats/sum2/item_9",
                sumimg3: "hats/sum3/item_9",
                oprice: "",
                dprice: "12900",
                review: "",
                color: ["Black", "Pink"],
                size: ["FREE"],
            },
            {   idx: 9,
                name: "리본 밀짚모자",
                img: "ac/hats/item_10",
                wsimg: "kids/ac/hats/item_10",
                sumimg2: "hats/sum2/item_10",
                sumimg3: "hats/sum3/item_10",
                oprice: "",
                dprice: "15900",
                review: "72",
                color: ["Pink", "Beige"],
                size: ["FREE"],
            },
            {   idx: 10,
                name: "푸우 양면 버킷햇",
                img: "ac/hats/item_11",
                wsimg: "kids/ac/hats/item_11",
                sumimg2: "hats/sum2/item_11",
                sumimg3: "hats/sum3/item_11",
                oprice: "",
                dprice: "29900",
                review: "",
                color: ["Black", "Yellow"],
                size: ["FREE"],
            },
            {   idx: 11,
                name: "울 헌팅캡",
                img: "ac/hats/item_12",
                wsimg: "kids/ac/hats/item_12",
                sumimg2: "hats/sum2/item_12",
                sumimg3: "hats/sum3/item_12",
                oprice: "",
                dprice: "29900",
                review: "72",
                color: ["Charcoal"],
                size: ["FREE"],
            },
        ],
    },
}

export default kidsData;